// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module array_mult_array_mult_Pipeline_VITIS_LOOP_26_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_a_TVALID,
        in_a_store_data_4_address0,
        in_a_store_data_4_ce0,
        in_a_store_data_4_we0,
        in_a_store_data_4_d0,
        in_a_store_data_3_address0,
        in_a_store_data_3_ce0,
        in_a_store_data_3_we0,
        in_a_store_data_3_d0,
        in_a_store_data_2_address0,
        in_a_store_data_2_ce0,
        in_a_store_data_2_we0,
        in_a_store_data_2_d0,
        in_a_store_data_1_address0,
        in_a_store_data_1_ce0,
        in_a_store_data_1_we0,
        in_a_store_data_1_d0,
        in_a_store_data_address0,
        in_a_store_data_ce0,
        in_a_store_data_we0,
        in_a_store_data_d0,
        in_a_store_keep_address0,
        in_a_store_keep_ce0,
        in_a_store_keep_we0,
        in_a_store_keep_d0,
        in_a_store_strb_address0,
        in_a_store_strb_ce0,
        in_a_store_strb_we0,
        in_a_store_strb_d0,
        in_a_store_last_address0,
        in_a_store_last_ce0,
        in_a_store_last_we0,
        in_a_store_last_d0,
        in_a_TDATA,
        in_a_TREADY,
        in_a_TKEEP,
        in_a_TSTRB,
        in_a_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_a_TVALID;
output  [2:0] in_a_store_data_4_address0;
output   in_a_store_data_4_ce0;
output   in_a_store_data_4_we0;
output  [31:0] in_a_store_data_4_d0;
output  [2:0] in_a_store_data_3_address0;
output   in_a_store_data_3_ce0;
output   in_a_store_data_3_we0;
output  [31:0] in_a_store_data_3_d0;
output  [2:0] in_a_store_data_2_address0;
output   in_a_store_data_2_ce0;
output   in_a_store_data_2_we0;
output  [31:0] in_a_store_data_2_d0;
output  [2:0] in_a_store_data_1_address0;
output   in_a_store_data_1_ce0;
output   in_a_store_data_1_we0;
output  [31:0] in_a_store_data_1_d0;
output  [2:0] in_a_store_data_address0;
output   in_a_store_data_ce0;
output   in_a_store_data_we0;
output  [31:0] in_a_store_data_d0;
output  [4:0] in_a_store_keep_address0;
output   in_a_store_keep_ce0;
output   in_a_store_keep_we0;
output  [3:0] in_a_store_keep_d0;
output  [4:0] in_a_store_strb_address0;
output   in_a_store_strb_ce0;
output   in_a_store_strb_we0;
output  [3:0] in_a_store_strb_d0;
output  [4:0] in_a_store_last_address0;
output   in_a_store_last_ce0;
output   in_a_store_last_we0;
output  [0:0] in_a_store_last_d0;
input  [31:0] in_a_TDATA;
output   in_a_TREADY;
input  [3:0] in_a_TKEEP;
input  [3:0] in_a_TSTRB;
input  [0:0] in_a_TLAST;

reg ap_idle;
reg in_a_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire   [0:0] icmp_ln26_fu_230_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_a_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln26_reg_359;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] p_s_reg_363;
wire   [63:0] zext_ln26_fu_242_p1;
wire   [63:0] zext_ln21_fu_295_p1;
reg   [4:0] phi_urem_fu_84;
wire   [4:0] select_ln27_fu_320_p3;
wire    ap_loop_init;
reg   [10:0] phi_mul_fu_88;
wire   [10:0] add_ln21_fu_279_p2;
reg   [4:0] i_fu_92;
wire   [4:0] add_ln26_fu_236_p2;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    in_a_store_keep_we0_local;
reg    in_a_store_keep_ce0_local;
reg    in_a_store_strb_we0_local;
reg    in_a_store_strb_ce0_local;
reg    in_a_store_last_we0_local;
reg    in_a_store_last_ce0_local;
reg    in_a_store_data_3_we0_local;
wire   [2:0] trunc_ln21_fu_304_p1;
reg    in_a_store_data_3_ce0_local;
reg    in_a_store_data_2_we0_local;
reg    in_a_store_data_2_ce0_local;
reg    in_a_store_data_1_we0_local;
reg    in_a_store_data_1_ce0_local;
reg    in_a_store_data_we0_local;
reg    in_a_store_data_ce0_local;
reg    in_a_store_data_4_we0_local;
reg    in_a_store_data_4_ce0_local;
wire   [2:0] tmp_fu_285_p4;
wire   [4:0] add_ln27_fu_308_p2;
wire   [0:0] icmp_ln27_1_fu_314_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 phi_urem_fu_84 = 5'd0;
#0 phi_mul_fu_88 = 11'd0;
#0 i_fu_92 = 5'd0;
#0 ap_done_reg = 1'b0;
end

array_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if (((ap_loop_exit_ready == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
            ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            i_fu_92 <= add_ln26_fu_236_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_92 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_mul_fu_88 <= 11'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln26_reg_359 == 1'd0))) begin
            phi_mul_fu_88 <= add_ln21_fu_279_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            phi_urem_fu_84 <= 5'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln26_reg_359 == 1'd0))) begin
            phi_urem_fu_84 <= select_ln27_fu_320_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln26_reg_359 <= icmp_ln26_fu_230_p2;
        p_s_reg_363 <= in_a_TDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln26_fu_230_p2 == 1'd1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_TDATA_blk_n = in_a_TVALID;
    end else begin
        in_a_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_TREADY = 1'b1;
    end else begin
        in_a_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_1_ce0_local = 1'b1;
    end else begin
        in_a_store_data_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln21_fu_304_p1 == 3'd1) & (icmp_ln26_reg_359 == 1'd0))) begin
        in_a_store_data_1_we0_local = 1'b1;
    end else begin
        in_a_store_data_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_2_ce0_local = 1'b1;
    end else begin
        in_a_store_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln21_fu_304_p1 == 3'd2) & (icmp_ln26_reg_359 == 1'd0))) begin
        in_a_store_data_2_we0_local = 1'b1;
    end else begin
        in_a_store_data_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_3_ce0_local = 1'b1;
    end else begin
        in_a_store_data_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln21_fu_304_p1 == 3'd3) & (icmp_ln26_reg_359 == 1'd0))) begin
        in_a_store_data_3_we0_local = 1'b1;
    end else begin
        in_a_store_data_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_4_ce0_local = 1'b1;
    end else begin
        in_a_store_data_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln21_fu_304_p1 == 3'd0) & ~(trunc_ln21_fu_304_p1 == 3'd1) & ~(trunc_ln21_fu_304_p1 == 3'd2) & ~(trunc_ln21_fu_304_p1 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln26_reg_359 == 1'd0))) begin
        in_a_store_data_4_we0_local = 1'b1;
    end else begin
        in_a_store_data_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_ce0_local = 1'b1;
    end else begin
        in_a_store_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln21_fu_304_p1 == 3'd0) & (icmp_ln26_reg_359 == 1'd0))) begin
        in_a_store_data_we0_local = 1'b1;
    end else begin
        in_a_store_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_keep_ce0_local = 1'b1;
    end else begin
        in_a_store_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_keep_we0_local = 1'b1;
    end else begin
        in_a_store_keep_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_last_ce0_local = 1'b1;
    end else begin
        in_a_store_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_last_we0_local = 1'b1;
    end else begin
        in_a_store_last_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_strb_ce0_local = 1'b1;
    end else begin
        in_a_store_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln26_fu_230_p2 == 1'd0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_strb_we0_local = 1'b1;
    end else begin
        in_a_store_strb_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_fu_279_p2 = (phi_mul_fu_88 + 11'd52);

assign add_ln26_fu_236_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign add_ln27_fu_308_p2 = (phi_urem_fu_84 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start_int == 1'b1) & (1'b1 == ap_block_state1_pp0_stage0_iter0));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((icmp_ln26_fu_230_p2 == 1'd0) & (in_a_TVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln26_fu_230_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln27_1_fu_314_p2 = ((add_ln27_fu_308_p2 < 5'd5) ? 1'b1 : 1'b0);

assign in_a_store_data_1_address0 = zext_ln21_fu_295_p1;

assign in_a_store_data_1_ce0 = in_a_store_data_1_ce0_local;

assign in_a_store_data_1_d0 = p_s_reg_363;

assign in_a_store_data_1_we0 = in_a_store_data_1_we0_local;

assign in_a_store_data_2_address0 = zext_ln21_fu_295_p1;

assign in_a_store_data_2_ce0 = in_a_store_data_2_ce0_local;

assign in_a_store_data_2_d0 = p_s_reg_363;

assign in_a_store_data_2_we0 = in_a_store_data_2_we0_local;

assign in_a_store_data_3_address0 = zext_ln21_fu_295_p1;

assign in_a_store_data_3_ce0 = in_a_store_data_3_ce0_local;

assign in_a_store_data_3_d0 = p_s_reg_363;

assign in_a_store_data_3_we0 = in_a_store_data_3_we0_local;

assign in_a_store_data_4_address0 = zext_ln21_fu_295_p1;

assign in_a_store_data_4_ce0 = in_a_store_data_4_ce0_local;

assign in_a_store_data_4_d0 = p_s_reg_363;

assign in_a_store_data_4_we0 = in_a_store_data_4_we0_local;

assign in_a_store_data_address0 = zext_ln21_fu_295_p1;

assign in_a_store_data_ce0 = in_a_store_data_ce0_local;

assign in_a_store_data_d0 = p_s_reg_363;

assign in_a_store_data_we0 = in_a_store_data_we0_local;

assign in_a_store_keep_address0 = zext_ln26_fu_242_p1;

assign in_a_store_keep_ce0 = in_a_store_keep_ce0_local;

assign in_a_store_keep_d0 = in_a_TKEEP;

assign in_a_store_keep_we0 = in_a_store_keep_we0_local;

assign in_a_store_last_address0 = zext_ln26_fu_242_p1;

assign in_a_store_last_ce0 = in_a_store_last_ce0_local;

assign in_a_store_last_d0 = in_a_TLAST;

assign in_a_store_last_we0 = in_a_store_last_we0_local;

assign in_a_store_strb_address0 = zext_ln26_fu_242_p1;

assign in_a_store_strb_ce0 = in_a_store_strb_ce0_local;

assign in_a_store_strb_d0 = in_a_TSTRB;

assign in_a_store_strb_we0 = in_a_store_strb_we0_local;

assign select_ln27_fu_320_p3 = ((icmp_ln27_1_fu_314_p2[0:0] == 1'b1) ? add_ln27_fu_308_p2 : 5'd0);

assign tmp_fu_285_p4 = {{phi_mul_fu_88[10:8]}};

assign trunc_ln21_fu_304_p1 = phi_urem_fu_84[2:0];

assign zext_ln21_fu_295_p1 = tmp_fu_285_p4;

assign zext_ln26_fu_242_p1 = ap_sig_allocacmp_i_1;

endmodule //array_mult_array_mult_Pipeline_VITIS_LOOP_26_1
