// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module array_mult_array_mult_Pipeline_ROWS_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        result_TREADY,
        in_a_store_data_address0,
        in_a_store_data_ce0,
        in_a_store_data_q0,
        in_a_store_data_1_address0,
        in_a_store_data_1_ce0,
        in_a_store_data_1_q0,
        in_a_store_data_2_address0,
        in_a_store_data_2_ce0,
        in_a_store_data_2_q0,
        in_a_store_data_3_address0,
        in_a_store_data_3_ce0,
        in_a_store_data_3_q0,
        in_a_store_data_4_address0,
        in_a_store_data_4_ce0,
        in_a_store_data_4_q0,
        in_b_load_2,
        in_b_load_4,
        in_b_load_3,
        in_b_load,
        in_b_load_1,
        in_a_store_keep_address0,
        in_a_store_keep_ce0,
        in_a_store_keep_q0,
        in_a_store_strb_address0,
        in_a_store_strb_ce0,
        in_a_store_strb_q0,
        result_TDATA,
        result_TVALID,
        result_TKEEP,
        result_TSTRB,
        result_TLAST,
        in_b_load_7,
        in_b_load_9,
        in_b_load_8,
        in_b_load_5,
        in_b_load_6,
        in_b_load_12,
        in_b_load_14,
        in_b_load_13,
        in_b_load_10,
        in_b_load_11,
        in_b_load_17,
        in_b_load_19,
        in_b_load_18,
        in_b_load_15,
        in_b_load_16,
        in_b_load_22,
        in_b_load_24,
        in_b_load_23,
        in_b_load_20,
        in_b_load_21,
        in_a_store_last_address0,
        in_a_store_last_ce0,
        in_a_store_last_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   result_TREADY;
output  [2:0] in_a_store_data_address0;
output   in_a_store_data_ce0;
input  [31:0] in_a_store_data_q0;
output  [2:0] in_a_store_data_1_address0;
output   in_a_store_data_1_ce0;
input  [31:0] in_a_store_data_1_q0;
output  [2:0] in_a_store_data_2_address0;
output   in_a_store_data_2_ce0;
input  [31:0] in_a_store_data_2_q0;
output  [2:0] in_a_store_data_3_address0;
output   in_a_store_data_3_ce0;
input  [31:0] in_a_store_data_3_q0;
output  [2:0] in_a_store_data_4_address0;
output   in_a_store_data_4_ce0;
input  [31:0] in_a_store_data_4_q0;
input  [31:0] in_b_load_2;
input  [31:0] in_b_load_4;
input  [31:0] in_b_load_3;
input  [31:0] in_b_load;
input  [31:0] in_b_load_1;
output  [4:0] in_a_store_keep_address0;
output   in_a_store_keep_ce0;
input  [3:0] in_a_store_keep_q0;
output  [4:0] in_a_store_strb_address0;
output   in_a_store_strb_ce0;
input  [3:0] in_a_store_strb_q0;
output  [31:0] result_TDATA;
output   result_TVALID;
output  [3:0] result_TKEEP;
output  [3:0] result_TSTRB;
output  [0:0] result_TLAST;
input  [31:0] in_b_load_7;
input  [31:0] in_b_load_9;
input  [31:0] in_b_load_8;
input  [31:0] in_b_load_5;
input  [31:0] in_b_load_6;
input  [31:0] in_b_load_12;
input  [31:0] in_b_load_14;
input  [31:0] in_b_load_13;
input  [31:0] in_b_load_10;
input  [31:0] in_b_load_11;
input  [31:0] in_b_load_17;
input  [31:0] in_b_load_19;
input  [31:0] in_b_load_18;
input  [31:0] in_b_load_15;
input  [31:0] in_b_load_16;
input  [31:0] in_b_load_22;
input  [31:0] in_b_load_24;
input  [31:0] in_b_load_23;
input  [31:0] in_b_load_20;
input  [31:0] in_b_load_21;
output  [4:0] in_a_store_last_address0;
output   in_a_store_last_ce0;
input  [0:0] in_a_store_last_q0;

reg ap_idle;
reg[31:0] result_TDATA;
reg result_TVALID;
reg[3:0] result_TKEEP;
reg[3:0] result_TSTRB;
reg[0:0] result_TLAST;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
reg    ap_block_state10_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln30_reg_700;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    result_TDATA_blk_n;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire   [31:0] grp_fu_399_p2;
reg   [31:0] reg_419;
reg    ap_block_state9_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    ap_block_state7_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_11001;
reg    ap_block_state8_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
wire   [31:0] grp_fu_403_p2;
reg   [31:0] reg_423;
wire   [31:0] grp_fu_407_p2;
reg   [31:0] reg_427;
wire   [31:0] grp_fu_411_p2;
reg   [31:0] reg_431;
wire   [31:0] grp_fu_415_p2;
reg   [31:0] reg_435;
reg   [31:0] reg_439;
reg   [31:0] reg_443;
wire   [31:0] grp_fu_453_p2;
reg   [31:0] reg_471;
reg   [2:0] i_reg_693;
wire   [0:0] icmp_ln30_fu_497_p2;
reg  signed [31:0] in_a_store_data_load_reg_729;
reg  signed [31:0] in_a_store_data_1_load_reg_734;
reg  signed [31:0] in_a_store_data_2_load_reg_739;
reg  signed [31:0] in_a_store_data_3_load_reg_744;
wire   [63:0] zext_ln40_1_fu_539_p1;
reg   [63:0] zext_ln40_1_reg_749;
reg  signed [31:0] in_a_store_data_4_load_reg_754;
reg   [3:0] mult_acc_keep_reg_769;
reg   [3:0] mult_acc_keep_reg_769_pp0_iter1_reg;
reg   [3:0] mult_acc_strb_reg_774;
reg   [3:0] mult_acc_strb_reg_774_pp0_iter1_reg;
reg   [31:0] mul_ln40_23_reg_784;
reg   [31:0] mul_ln40_24_reg_789;
reg   [0:0] mult_acc_last_reg_794;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln30_fu_503_p1;
reg   [2:0] i_1_fu_124;
wire   [2:0] add_ln30_fu_512_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i;
wire   [31:0] grp_fu_475_p2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_482_p2;
reg    ap_block_pp0_stage1_01001;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
wire   [31:0] mult_acc_data_4_fu_554_p2;
reg    ap_block_pp0_stage4_01001;
reg    in_a_store_data_ce0_local;
reg    in_a_store_data_1_ce0_local;
reg    in_a_store_data_2_ce0_local;
reg    in_a_store_data_3_ce0_local;
reg    in_a_store_data_4_ce0_local;
reg    in_a_store_keep_ce0_local;
reg    in_a_store_strb_ce0_local;
reg    in_a_store_last_ce0_local;
reg  signed [31:0] grp_fu_399_p1;
reg  signed [31:0] grp_fu_403_p1;
reg  signed [31:0] grp_fu_407_p1;
reg  signed [31:0] grp_fu_411_p1;
reg  signed [31:0] grp_fu_415_p1;
wire   [31:0] grp_fu_447_p2;
wire   [31:0] grp_fu_459_p2;
wire   [31:0] grp_fu_465_p2;
wire   [4:0] p_shl_fu_520_p3;
wire   [4:0] zext_ln40_fu_517_p1;
wire   [4:0] add_ln40_4_fu_527_p2;
wire   [4:0] add_ln40_fu_533_p2;
wire   [31:0] add_ln40_17_fu_550_p2;
reg    grp_fu_399_ce;
reg    grp_fu_403_ce;
reg    grp_fu_407_ce;
reg    grp_fu_411_ce;
reg    grp_fu_415_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_1_fu_124 = 3'd0;
#0 ap_done_reg = 1'b0;
end

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in_a_store_data_2_load_reg_739),
    .din1(grp_fu_399_p1),
    .ce(grp_fu_399_ce),
    .dout(grp_fu_399_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in_a_store_data_4_load_reg_754),
    .din1(grp_fu_403_p1),
    .ce(grp_fu_403_ce),
    .dout(grp_fu_403_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in_a_store_data_3_load_reg_744),
    .din1(grp_fu_407_p1),
    .ce(grp_fu_407_ce),
    .dout(grp_fu_407_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in_a_store_data_load_reg_729),
    .din1(grp_fu_411_p1),
    .ce(grp_fu_411_ce),
    .dout(grp_fu_411_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(in_a_store_data_1_load_reg_734),
    .din1(grp_fu_415_p1),
    .ce(grp_fu_415_ce),
    .dout(grp_fu_415_p2)
);

array_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_1_fu_124 <= 3'd0;
    end else if (((icmp_ln30_reg_700 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_1_fu_124 <= add_ln30_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_693 <= ap_sig_allocacmp_i;
        icmp_ln30_reg_700 <= icmp_ln30_fu_497_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_data_1_load_reg_734 <= in_a_store_data_1_q0;
        in_a_store_data_2_load_reg_739 <= in_a_store_data_2_q0;
        in_a_store_data_3_load_reg_744 <= in_a_store_data_3_q0;
        in_a_store_data_4_load_reg_754 <= in_a_store_data_4_q0;
        in_a_store_data_load_reg_729 <= in_a_store_data_q0;
        zext_ln40_1_reg_749[4 : 0] <= zext_ln40_1_fu_539_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln40_23_reg_784 <= grp_fu_411_p2;
        mul_ln40_24_reg_789 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mult_acc_keep_reg_769 <= in_a_store_keep_q0;
        mult_acc_keep_reg_769_pp0_iter1_reg <= mult_acc_keep_reg_769;
        mult_acc_last_reg_794 <= in_a_store_last_q0;
        mult_acc_strb_reg_774 <= in_a_store_strb_q0;
        mult_acc_strb_reg_774_pp0_iter1_reg <= mult_acc_strb_reg_774;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_419 <= grp_fu_399_p2;
        reg_423 <= grp_fu_403_p2;
        reg_427 <= grp_fu_407_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_431 <= grp_fu_411_p2;
        reg_435 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_439 <= grp_fu_411_p2;
        reg_443 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_471 <= grp_fu_453_p2;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_700 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 3'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_124;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_399_ce = 1'b1;
    end else begin
        grp_fu_399_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_399_p1 = in_b_load_22;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_399_p1 = in_b_load_17;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_399_p1 = in_b_load_12;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_399_p1 = in_b_load_7;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_399_p1 = in_b_load_2;
    end else begin
        grp_fu_399_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_403_ce = 1'b1;
    end else begin
        grp_fu_403_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_403_p1 = in_b_load_24;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_403_p1 = in_b_load_19;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_403_p1 = in_b_load_14;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_403_p1 = in_b_load_9;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_403_p1 = in_b_load_4;
    end else begin
        grp_fu_403_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_407_ce = 1'b1;
    end else begin
        grp_fu_407_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_407_p1 = in_b_load_23;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_407_p1 = in_b_load_18;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_407_p1 = in_b_load_13;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_407_p1 = in_b_load_8;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_407_p1 = in_b_load_3;
    end else begin
        grp_fu_407_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_411_ce = 1'b1;
    end else begin
        grp_fu_411_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_411_p1 = in_b_load_20;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_411_p1 = in_b_load_15;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_411_p1 = in_b_load_10;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_411_p1 = in_b_load_5;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_411_p1 = in_b_load;
    end else begin
        grp_fu_411_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_415_ce = 1'b1;
    end else begin
        grp_fu_415_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_415_p1 = in_b_load_21;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_415_p1 = in_b_load_16;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_415_p1 = in_b_load_11;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_415_p1 = in_b_load_6;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_415_p1 = in_b_load_1;
    end else begin
        grp_fu_415_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_1_ce0_local = 1'b1;
    end else begin
        in_a_store_data_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_2_ce0_local = 1'b1;
    end else begin
        in_a_store_data_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_3_ce0_local = 1'b1;
    end else begin
        in_a_store_data_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_4_ce0_local = 1'b1;
    end else begin
        in_a_store_data_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_a_store_data_ce0_local = 1'b1;
    end else begin
        in_a_store_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_keep_ce0_local = 1'b1;
    end else begin
        in_a_store_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_last_ce0_local = 1'b1;
    end else begin
        in_a_store_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_strb_ce0_local = 1'b1;
    end else begin
        in_a_store_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        result_TDATA = mult_acc_data_4_fu_554_p2;
    end else if ((((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        result_TDATA = grp_fu_482_p2;
    end else if ((((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        result_TDATA = grp_fu_475_p2;
    end else begin
        result_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        result_TDATA_blk_n = result_TREADY;
    end else begin
        result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TKEEP = mult_acc_keep_reg_769_pp0_iter1_reg;
    end else if ((((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        result_TKEEP = mult_acc_keep_reg_769;
    end else begin
        result_TKEEP = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        result_TLAST = mult_acc_last_reg_794;
    end else if ((((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        result_TLAST = 1'd0;
    end else begin
        result_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TSTRB = mult_acc_strb_reg_774_pp0_iter1_reg;
    end else if ((((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        result_TSTRB = mult_acc_strb_reg_774;
    end else begin
        result_TSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TVALID = 1'b1;
    end else begin
        result_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_fu_512_p2 = (i_reg_693 + 3'd1);

assign add_ln40_17_fu_550_p2 = (mul_ln40_24_reg_789 + mul_ln40_23_reg_784);

assign add_ln40_4_fu_527_p2 = (p_shl_fu_520_p3 + zext_ln40_fu_517_p1);

assign add_ln40_fu_533_p2 = (add_ln40_4_fu_527_p2 + 5'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state6_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage1_iter1));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state7_pp0_stage1_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state7_pp0_stage1_iter1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage2_iter1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state8_pp0_stage2_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state8_pp0_stage2_iter1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage3_iter1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state9_pp0_stage3_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state9_pp0_stage3_iter1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage4_iter1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage4_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage4_iter1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage4_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state7_pp0_stage1_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp0_stage2_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage3_iter1 = (result_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign grp_fu_447_p2 = (reg_427 + reg_423);

assign grp_fu_453_p2 = (grp_fu_447_p2 + reg_419);

assign grp_fu_459_p2 = (reg_435 + reg_431);

assign grp_fu_465_p2 = (reg_443 + reg_439);

assign grp_fu_475_p2 = (reg_471 + grp_fu_459_p2);

assign grp_fu_482_p2 = (reg_471 + grp_fu_465_p2);

assign icmp_ln30_fu_497_p2 = ((ap_sig_allocacmp_i == 3'd5) ? 1'b1 : 1'b0);

assign in_a_store_data_1_address0 = zext_ln30_fu_503_p1;

assign in_a_store_data_1_ce0 = in_a_store_data_1_ce0_local;

assign in_a_store_data_2_address0 = zext_ln30_fu_503_p1;

assign in_a_store_data_2_ce0 = in_a_store_data_2_ce0_local;

assign in_a_store_data_3_address0 = zext_ln30_fu_503_p1;

assign in_a_store_data_3_ce0 = in_a_store_data_3_ce0_local;

assign in_a_store_data_4_address0 = zext_ln30_fu_503_p1;

assign in_a_store_data_4_ce0 = in_a_store_data_4_ce0_local;

assign in_a_store_data_address0 = zext_ln30_fu_503_p1;

assign in_a_store_data_ce0 = in_a_store_data_ce0_local;

assign in_a_store_keep_address0 = zext_ln40_1_fu_539_p1;

assign in_a_store_keep_ce0 = in_a_store_keep_ce0_local;

assign in_a_store_last_address0 = zext_ln40_1_reg_749;

assign in_a_store_last_ce0 = in_a_store_last_ce0_local;

assign in_a_store_strb_address0 = zext_ln40_1_fu_539_p1;

assign in_a_store_strb_ce0 = in_a_store_strb_ce0_local;

assign mult_acc_data_4_fu_554_p2 = (reg_471 + add_ln40_17_fu_550_p2);

assign p_shl_fu_520_p3 = {{i_reg_693}, {2'd0}};

assign zext_ln30_fu_503_p1 = ap_sig_allocacmp_i;

assign zext_ln40_1_fu_539_p1 = add_ln40_fu_533_p2;

assign zext_ln40_fu_517_p1 = i_reg_693;

always @ (posedge ap_clk) begin
    zext_ln40_1_reg_749[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //array_mult_array_mult_Pipeline_ROWS_LOOP
