-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity array_mult is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32;
    C_S_AXI_DATA_IN_B_ADDR_WIDTH : INTEGER := 8;
    C_S_AXI_DATA_IN_B_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_a_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_a_TVALID : IN STD_LOGIC;
    in_a_TREADY : OUT STD_LOGIC;
    in_a_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_a_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_a_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    result_TVALID : OUT STD_LOGIC;
    result_TREADY : IN STD_LOGIC;
    result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    s_axi_DATA_IN_B_AWVALID : IN STD_LOGIC;
    s_axi_DATA_IN_B_AWREADY : OUT STD_LOGIC;
    s_axi_DATA_IN_B_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_IN_B_ADDR_WIDTH-1 downto 0);
    s_axi_DATA_IN_B_WVALID : IN STD_LOGIC;
    s_axi_DATA_IN_B_WREADY : OUT STD_LOGIC;
    s_axi_DATA_IN_B_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_IN_B_DATA_WIDTH-1 downto 0);
    s_axi_DATA_IN_B_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_IN_B_DATA_WIDTH/8-1 downto 0);
    s_axi_DATA_IN_B_ARVALID : IN STD_LOGIC;
    s_axi_DATA_IN_B_ARREADY : OUT STD_LOGIC;
    s_axi_DATA_IN_B_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_IN_B_ADDR_WIDTH-1 downto 0);
    s_axi_DATA_IN_B_RVALID : OUT STD_LOGIC;
    s_axi_DATA_IN_B_RREADY : IN STD_LOGIC;
    s_axi_DATA_IN_B_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_IN_B_DATA_WIDTH-1 downto 0);
    s_axi_DATA_IN_B_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_DATA_IN_B_BVALID : OUT STD_LOGIC;
    s_axi_DATA_IN_B_BREADY : IN STD_LOGIC;
    s_axi_DATA_IN_B_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of array_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "array_mult_array_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.079540,HLS_SYN_LAT=90,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2910,HLS_SYN_LUT=2169,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (30 downto 0) := "0000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (30 downto 0) := "0000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (30 downto 0) := "0000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (30 downto 0) := "0000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (30 downto 0) := "0000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (30 downto 0) := "0000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (30 downto 0) := "0001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (30 downto 0) := "0010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (30 downto 0) := "0100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (30 downto 0) := "1000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_A : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001010";
    constant ap_const_lv64_F : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001111";
    constant ap_const_lv64_14 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010100";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_B : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001011";
    constant ap_const_lv64_10 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010000";
    constant ap_const_lv64_15 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_C : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001100";
    constant ap_const_lv64_11 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010001";
    constant ap_const_lv64_16 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010110";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_8 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001000";
    constant ap_const_lv64_D : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001101";
    constant ap_const_lv64_12 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010010";
    constant ap_const_lv64_17 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010111";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001001";
    constant ap_const_lv64_E : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000001110";
    constant ap_const_lv64_13 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000010011";
    constant ap_const_lv64_18 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000011000";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal in_b_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal in_b_load_reg_427 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal in_b_load_1_reg_437 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal in_b_load_2_reg_447 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal in_b_load_3_reg_457 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal in_b_load_4_reg_467 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal in_b_load_5_reg_477 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal in_b_load_6_reg_487 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal in_b_load_7_reg_497 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal in_b_load_8_reg_507 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal in_b_load_9_reg_517 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal in_b_load_10_reg_527 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal in_b_load_11_reg_537 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal in_b_load_12_reg_547 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal in_b_load_13_reg_557 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal in_b_load_14_reg_567 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal in_b_load_15_reg_577 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal in_b_load_16_reg_587 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal in_b_load_17_reg_597 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal in_b_load_18_reg_607 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal in_b_load_19_reg_617 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal in_b_load_20_reg_627 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal in_b_load_21_reg_637 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal in_b_load_22_reg_647 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal in_b_load_23_reg_657 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state28 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state28 : signal is "none";
    signal in_b_load_24_reg_667 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state29 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state29 : signal is "none";
    signal in_a_store_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal in_a_store_data_ce0 : STD_LOGIC;
    signal in_a_store_data_we0 : STD_LOGIC;
    signal in_a_store_data_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_a_store_data_ce1 : STD_LOGIC;
    signal in_a_store_data_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in_a_store_keep_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal in_a_store_keep_ce0 : STD_LOGIC;
    signal in_a_store_keep_we0 : STD_LOGIC;
    signal in_a_store_keep_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal in_a_store_strb_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal in_a_store_strb_ce0 : STD_LOGIC;
    signal in_a_store_strb_we0 : STD_LOGIC;
    signal in_a_store_strb_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal in_a_store_last_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal in_a_store_last_ce0 : STD_LOGIC;
    signal in_a_store_last_we0 : STD_LOGIC;
    signal in_a_store_last_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_idle : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_idle : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0 : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1 : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID : STD_LOGIC;
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state30 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state30 : signal is "none";
    signal in_b_ce0_local : STD_LOGIC;
    signal in_b_address0_local : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state31 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state31 : signal is "none";
    signal regslice_both_result_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal regslice_both_in_a_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_a_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_a_TVALID_int_regslice : STD_LOGIC;
    signal in_a_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_a_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_a_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_a_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_a_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_a_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_a_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_a_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_a_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_a_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_a_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_a_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_a_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_a_V_last_V_U_ack_in : STD_LOGIC;
    signal result_TVALID_int_regslice : STD_LOGIC;
    signal result_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_result_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_result_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component array_mult_array_mult_Pipeline_VITIS_LOOP_26_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_a_TVALID : IN STD_LOGIC;
        in_a_store_data_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_data_ce0 : OUT STD_LOGIC;
        in_a_store_data_we0 : OUT STD_LOGIC;
        in_a_store_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_a_store_keep_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_keep_ce0 : OUT STD_LOGIC;
        in_a_store_keep_we0 : OUT STD_LOGIC;
        in_a_store_keep_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_a_store_strb_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_strb_ce0 : OUT STD_LOGIC;
        in_a_store_strb_we0 : OUT STD_LOGIC;
        in_a_store_strb_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        in_a_store_last_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_last_ce0 : OUT STD_LOGIC;
        in_a_store_last_we0 : OUT STD_LOGIC;
        in_a_store_last_d0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        in_a_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_a_TREADY : OUT STD_LOGIC;
        in_a_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_a_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_a_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component array_mult_array_mult_Pipeline_ROWS_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        result_TREADY : IN STD_LOGIC;
        in_a_store_last_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_last_ce0 : OUT STD_LOGIC;
        in_a_store_last_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        in_a_store_keep_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_keep_ce0 : OUT STD_LOGIC;
        in_a_store_keep_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
        in_a_store_strb_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_strb_ce0 : OUT STD_LOGIC;
        in_a_store_strb_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
        in_a_store_data_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_data_ce0 : OUT STD_LOGIC;
        in_a_store_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_a_store_data_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_a_store_data_ce1 : OUT STD_LOGIC;
        in_a_store_data_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_3 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_4 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_1 : IN STD_LOGIC_VECTOR (31 downto 0);
        result_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        result_TVALID : OUT STD_LOGIC;
        result_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        result_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        result_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        in_b_load_8 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_9 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_5 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_7 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_6 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_13 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_14 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_10 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_12 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_11 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_18 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_19 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_15 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_17 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_16 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_23 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_24 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_20 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_22 : IN STD_LOGIC_VECTOR (31 downto 0);
        in_b_load_21 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component array_mult_in_a_store_data_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component array_mult_in_a_store_keep_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (3 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component array_mult_in_a_store_last_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component array_mult_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component array_mult_DATA_IN_B_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_b_address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        in_b_ce0 : IN STD_LOGIC;
        in_b_q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component array_mult_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    in_a_store_data_U : component array_mult_in_a_store_data_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => in_a_store_data_address0,
        ce0 => in_a_store_data_ce0,
        we0 => in_a_store_data_we0,
        d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0,
        q0 => in_a_store_data_q0,
        address1 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1,
        ce1 => in_a_store_data_ce1,
        q1 => in_a_store_data_q1);

    in_a_store_keep_U : component array_mult_in_a_store_keep_RAM_AUTO_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => in_a_store_keep_address0,
        ce0 => in_a_store_keep_ce0,
        we0 => in_a_store_keep_we0,
        d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0,
        q0 => in_a_store_keep_q0);

    in_a_store_strb_U : component array_mult_in_a_store_keep_RAM_AUTO_1R1W
    generic map (
        DataWidth => 4,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => in_a_store_strb_address0,
        ce0 => in_a_store_strb_ce0,
        we0 => in_a_store_strb_we0,
        d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0,
        q0 => in_a_store_strb_q0);

    in_a_store_last_U : component array_mult_in_a_store_last_RAM_AUTO_1R1W
    generic map (
        DataWidth => 1,
        AddressRange => 25,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => in_a_store_last_address0,
        ce0 => in_a_store_last_ce0,
        we0 => in_a_store_last_we0,
        d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0,
        q0 => in_a_store_last_q0);

    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364 : component array_mult_array_mult_Pipeline_VITIS_LOOP_26_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start,
        ap_done => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done,
        ap_idle => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_idle,
        ap_ready => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready,
        in_a_TVALID => in_a_TVALID_int_regslice,
        in_a_store_data_address0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0,
        in_a_store_data_ce0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0,
        in_a_store_data_we0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0,
        in_a_store_data_d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0,
        in_a_store_keep_address0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0,
        in_a_store_keep_ce0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0,
        in_a_store_keep_we0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0,
        in_a_store_keep_d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0,
        in_a_store_strb_address0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0,
        in_a_store_strb_ce0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0,
        in_a_store_strb_we0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0,
        in_a_store_strb_d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0,
        in_a_store_last_address0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0,
        in_a_store_last_ce0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0,
        in_a_store_last_we0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0,
        in_a_store_last_d0 => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0,
        in_a_TDATA => in_a_TDATA_int_regslice,
        in_a_TREADY => grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY,
        in_a_TKEEP => in_a_TKEEP_int_regslice,
        in_a_TSTRB => in_a_TSTRB_int_regslice,
        in_a_TLAST => in_a_TLAST_int_regslice);

    grp_array_mult_Pipeline_ROWS_LOOP_fu_380 : component array_mult_array_mult_Pipeline_ROWS_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start,
        ap_done => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done,
        ap_idle => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_idle,
        ap_ready => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready,
        result_TREADY => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY,
        in_a_store_last_address0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0,
        in_a_store_last_ce0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0,
        in_a_store_last_q0 => in_a_store_last_q0,
        in_a_store_keep_address0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0,
        in_a_store_keep_ce0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0,
        in_a_store_keep_q0 => in_a_store_keep_q0,
        in_a_store_strb_address0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0,
        in_a_store_strb_ce0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0,
        in_a_store_strb_q0 => in_a_store_strb_q0,
        in_a_store_data_address0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0,
        in_a_store_data_ce0 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0,
        in_a_store_data_q0 => in_a_store_data_q0,
        in_a_store_data_address1 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1,
        in_a_store_data_ce1 => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1,
        in_a_store_data_q1 => in_a_store_data_q1,
        in_b_load_3 => in_b_load_3_reg_457,
        in_b_load_4 => in_b_load_4_reg_467,
        in_b_load => in_b_load_reg_427,
        in_b_load_2 => in_b_load_2_reg_447,
        in_b_load_1 => in_b_load_1_reg_437,
        result_TDATA => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA,
        result_TVALID => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID,
        result_TKEEP => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP,
        result_TSTRB => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB,
        result_TLAST => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST,
        in_b_load_8 => in_b_load_8_reg_507,
        in_b_load_9 => in_b_load_9_reg_517,
        in_b_load_5 => in_b_load_5_reg_477,
        in_b_load_7 => in_b_load_7_reg_497,
        in_b_load_6 => in_b_load_6_reg_487,
        in_b_load_13 => in_b_load_13_reg_557,
        in_b_load_14 => in_b_load_14_reg_567,
        in_b_load_10 => in_b_load_10_reg_527,
        in_b_load_12 => in_b_load_12_reg_547,
        in_b_load_11 => in_b_load_11_reg_537,
        in_b_load_18 => in_b_load_18_reg_607,
        in_b_load_19 => in_b_load_19_reg_617,
        in_b_load_15 => in_b_load_15_reg_577,
        in_b_load_17 => in_b_load_17_reg_597,
        in_b_load_16 => in_b_load_16_reg_587,
        in_b_load_23 => in_b_load_23_reg_657,
        in_b_load_24 => in_b_load_24_reg_667,
        in_b_load_20 => in_b_load_20_reg_627,
        in_b_load_22 => in_b_load_22_reg_647,
        in_b_load_21 => in_b_load_21_reg_637);

    CTRL_s_axi_U : component array_mult_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    DATA_IN_B_s_axi_U : component array_mult_DATA_IN_B_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_DATA_IN_B_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_DATA_IN_B_DATA_WIDTH)
    port map (
        AWVALID => s_axi_DATA_IN_B_AWVALID,
        AWREADY => s_axi_DATA_IN_B_AWREADY,
        AWADDR => s_axi_DATA_IN_B_AWADDR,
        WVALID => s_axi_DATA_IN_B_WVALID,
        WREADY => s_axi_DATA_IN_B_WREADY,
        WDATA => s_axi_DATA_IN_B_WDATA,
        WSTRB => s_axi_DATA_IN_B_WSTRB,
        ARVALID => s_axi_DATA_IN_B_ARVALID,
        ARREADY => s_axi_DATA_IN_B_ARREADY,
        ARADDR => s_axi_DATA_IN_B_ARADDR,
        RVALID => s_axi_DATA_IN_B_RVALID,
        RREADY => s_axi_DATA_IN_B_RREADY,
        RDATA => s_axi_DATA_IN_B_RDATA,
        RRESP => s_axi_DATA_IN_B_RRESP,
        BVALID => s_axi_DATA_IN_B_BVALID,
        BREADY => s_axi_DATA_IN_B_BREADY,
        BRESP => s_axi_DATA_IN_B_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_b_address0 => in_b_address0_local,
        in_b_ce0 => in_b_ce0_local,
        in_b_q0 => in_b_q0);

    regslice_both_in_a_V_data_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_a_TDATA,
        vld_in => in_a_TVALID,
        ack_in => regslice_both_in_a_V_data_V_U_ack_in,
        data_out => in_a_TDATA_int_regslice,
        vld_out => in_a_TVALID_int_regslice,
        ack_out => in_a_TREADY_int_regslice,
        apdone_blk => regslice_both_in_a_V_data_V_U_apdone_blk);

    regslice_both_in_a_V_keep_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_a_TKEEP,
        vld_in => in_a_TVALID,
        ack_in => regslice_both_in_a_V_keep_V_U_ack_in,
        data_out => in_a_TKEEP_int_regslice,
        vld_out => regslice_both_in_a_V_keep_V_U_vld_out,
        ack_out => in_a_TREADY_int_regslice,
        apdone_blk => regslice_both_in_a_V_keep_V_U_apdone_blk);

    regslice_both_in_a_V_strb_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_a_TSTRB,
        vld_in => in_a_TVALID,
        ack_in => regslice_both_in_a_V_strb_V_U_ack_in,
        data_out => in_a_TSTRB_int_regslice,
        vld_out => regslice_both_in_a_V_strb_V_U_vld_out,
        ack_out => in_a_TREADY_int_regslice,
        apdone_blk => regslice_both_in_a_V_strb_V_U_apdone_blk);

    regslice_both_in_a_V_last_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_a_TLAST,
        vld_in => in_a_TVALID,
        ack_in => regslice_both_in_a_V_last_V_U_ack_in,
        data_out => in_a_TLAST_int_regslice,
        vld_out => regslice_both_in_a_V_last_V_U_vld_out,
        ack_out => in_a_TREADY_int_regslice,
        apdone_blk => regslice_both_in_a_V_last_V_U_apdone_blk);

    regslice_both_result_V_data_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA,
        vld_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID,
        ack_in => result_TREADY_int_regslice,
        data_out => result_TDATA,
        vld_out => regslice_both_result_V_data_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_data_V_U_apdone_blk);

    regslice_both_result_V_keep_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP,
        vld_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID,
        ack_in => regslice_both_result_V_keep_V_U_ack_in_dummy,
        data_out => result_TKEEP,
        vld_out => regslice_both_result_V_keep_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_keep_V_U_apdone_blk);

    regslice_both_result_V_strb_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB,
        vld_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID,
        ack_in => regslice_both_result_V_strb_V_U_ack_in_dummy,
        data_out => result_TSTRB,
        vld_out => regslice_both_result_V_strb_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_strb_V_U_apdone_blk);

    regslice_both_result_V_last_V_U : component array_mult_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST,
        vld_in => grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID,
        ack_in => regslice_both_result_V_last_V_U_ack_in_dummy,
        data_out => result_TLAST,
        vld_out => regslice_both_result_V_last_V_U_vld_out,
        ack_out => result_TREADY,
        apdone_blk => regslice_both_result_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state29)) then 
                    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready = ap_const_logic_1)) then 
                    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready = ap_const_logic_1)) then 
                    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                in_b_load_10_reg_527 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                in_b_load_11_reg_537 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                in_b_load_12_reg_547 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                in_b_load_13_reg_557 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state19)) then
                in_b_load_14_reg_567 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state20)) then
                in_b_load_15_reg_577 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state21)) then
                in_b_load_16_reg_587 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                in_b_load_17_reg_597 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                in_b_load_18_reg_607 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state24)) then
                in_b_load_19_reg_617 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                in_b_load_1_reg_437 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then
                in_b_load_20_reg_627 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state26)) then
                in_b_load_21_reg_637 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state27)) then
                in_b_load_22_reg_647 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state28)) then
                in_b_load_23_reg_657 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state29)) then
                in_b_load_24_reg_667 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                in_b_load_2_reg_447 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                in_b_load_3_reg_457 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                in_b_load_4_reg_467 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                in_b_load_5_reg_477 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                in_b_load_6_reg_487 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                in_b_load_7_reg_497 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                in_b_load_8_reg_507 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                in_b_load_9_reg_517 <= in_b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                in_b_load_reg_427 <= in_b_q0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state30, ap_CS_fsm_state31, regslice_both_result_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                if (((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state30))) then
                    ap_NS_fsm <= ap_ST_fsm_state31;
                else
                    ap_NS_fsm <= ap_ST_fsm_state30;
                end if;
            when ap_ST_fsm_state31 => 
                if (((regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state31))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state31;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state28 <= ap_CS_fsm(27);
    ap_CS_fsm_state29 <= ap_CS_fsm(28);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state30 <= ap_CS_fsm(29);
    ap_CS_fsm_state31 <= ap_CS_fsm(30);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state30_blk_assign_proc : process(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done)
    begin
        if ((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state30_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state30_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state31_blk_assign_proc : process(regslice_both_result_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state31_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state31_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done)
    begin
        if ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state31, regslice_both_result_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state31, regslice_both_result_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_result_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state31))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg;
    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY <= (result_TREADY_int_regslice and ap_CS_fsm_state30);
    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg;
    in_a_TREADY <= regslice_both_in_a_V_data_V_U_ack_in;

    in_a_TREADY_int_regslice_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_TREADY_int_regslice <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY;
        else 
            in_a_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_data_address0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_data_address0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_data_address0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0;
        else 
            in_a_store_data_address0 <= "XXXXX";
        end if; 
    end process;


    in_a_store_data_ce0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_data_ce0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_data_ce0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0;
        else 
            in_a_store_data_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_data_ce1_assign_proc : process(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_data_ce1 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1;
        else 
            in_a_store_data_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_data_we0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_data_we0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0;
        else 
            in_a_store_data_we0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_keep_address0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_keep_address0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_keep_address0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0;
        else 
            in_a_store_keep_address0 <= "XXXXX";
        end if; 
    end process;


    in_a_store_keep_ce0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_keep_ce0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_keep_ce0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0;
        else 
            in_a_store_keep_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_keep_we0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_keep_we0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0;
        else 
            in_a_store_keep_we0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_last_address0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_last_address0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_last_address0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0;
        else 
            in_a_store_last_address0 <= "XXXXX";
        end if; 
    end process;


    in_a_store_last_ce0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_last_ce0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_last_ce0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0;
        else 
            in_a_store_last_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_last_we0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_last_we0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0;
        else 
            in_a_store_last_we0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_strb_address0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_strb_address0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_strb_address0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0;
        else 
            in_a_store_strb_address0 <= "XXXXX";
        end if; 
    end process;


    in_a_store_strb_ce0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0, grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0, ap_CS_fsm_state3, ap_CS_fsm_state30)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state30)) then 
            in_a_store_strb_ce0 <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_strb_ce0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0;
        else 
            in_a_store_strb_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    in_a_store_strb_we0_assign_proc : process(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_a_store_strb_we0 <= grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0;
        else 
            in_a_store_strb_we0 <= ap_const_logic_0;
        end if; 
    end process;


    in_b_address0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state26, ap_CS_fsm_state27, ap_CS_fsm_state28)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state28)) then 
            in_b_address0_local <= ap_const_lv64_18(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
            in_b_address0_local <= ap_const_lv64_13(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            in_b_address0_local <= ap_const_lv64_E(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            in_b_address0_local <= ap_const_lv64_9(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            in_b_address0_local <= ap_const_lv64_4(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            in_b_address0_local <= ap_const_lv64_17(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state22)) then 
            in_b_address0_local <= ap_const_lv64_12(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
            in_b_address0_local <= ap_const_lv64_D(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            in_b_address0_local <= ap_const_lv64_8(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            in_b_address0_local <= ap_const_lv64_3(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            in_b_address0_local <= ap_const_lv64_16(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            in_b_address0_local <= ap_const_lv64_11(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            in_b_address0_local <= ap_const_lv64_C(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            in_b_address0_local <= ap_const_lv64_7(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            in_b_address0_local <= ap_const_lv64_2(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            in_b_address0_local <= ap_const_lv64_15(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            in_b_address0_local <= ap_const_lv64_10(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            in_b_address0_local <= ap_const_lv64_B(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            in_b_address0_local <= ap_const_lv64_6(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            in_b_address0_local <= ap_const_lv64_1(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            in_b_address0_local <= ap_const_lv64_14(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            in_b_address0_local <= ap_const_lv64_F(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            in_b_address0_local <= ap_const_lv64_A(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_b_address0_local <= ap_const_lv64_5(5 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            in_b_address0_local <= ap_const_lv64_0(5 - 1 downto 0);
        else 
            in_b_address0_local <= "XXXXX";
        end if; 
    end process;


    in_b_ce0_local_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state18, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state21, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state24, ap_CS_fsm_state25, ap_CS_fsm_state26, ap_CS_fsm_state27, ap_CS_fsm_state28)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state28) or (ap_const_logic_1 = ap_CS_fsm_state27) or (ap_const_logic_1 = ap_CS_fsm_state26) or (ap_const_logic_1 = ap_CS_fsm_state25) or (ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state22) or (ap_const_logic_1 = ap_CS_fsm_state21) or (ap_const_logic_1 = ap_CS_fsm_state20) or (ap_const_logic_1 = ap_CS_fsm_state19) or (ap_const_logic_1 = ap_CS_fsm_state18) or (ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            in_b_ce0_local <= ap_const_logic_1;
        else 
            in_b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    result_TVALID <= regslice_both_result_V_data_V_U_vld_out;
    result_TVALID_int_regslice <= grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID;
end behav;
