// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module array_mult_array_mult_Pipeline_VITIS_LOOP_26_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_a_TVALID,
        in_a_store_data_address0,
        in_a_store_data_ce0,
        in_a_store_data_we0,
        in_a_store_data_d0,
        in_a_store_keep_address0,
        in_a_store_keep_ce0,
        in_a_store_keep_we0,
        in_a_store_keep_d0,
        in_a_store_strb_address0,
        in_a_store_strb_ce0,
        in_a_store_strb_we0,
        in_a_store_strb_d0,
        in_a_store_last_address0,
        in_a_store_last_ce0,
        in_a_store_last_we0,
        in_a_store_last_d0,
        in_a_TDATA,
        in_a_TREADY,
        in_a_TKEEP,
        in_a_TSTRB,
        in_a_TLAST
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   in_a_TVALID;
output  [4:0] in_a_store_data_address0;
output   in_a_store_data_ce0;
output   in_a_store_data_we0;
output  [31:0] in_a_store_data_d0;
output  [4:0] in_a_store_keep_address0;
output   in_a_store_keep_ce0;
output   in_a_store_keep_we0;
output  [3:0] in_a_store_keep_d0;
output  [4:0] in_a_store_strb_address0;
output   in_a_store_strb_ce0;
output   in_a_store_strb_we0;
output  [3:0] in_a_store_strb_d0;
output  [4:0] in_a_store_last_address0;
output   in_a_store_last_ce0;
output   in_a_store_last_we0;
output  [0:0] in_a_store_last_d0;
input  [31:0] in_a_TDATA;
output   in_a_TREADY;
input  [3:0] in_a_TKEEP;
input  [3:0] in_a_TSTRB;
input  [0:0] in_a_TLAST;

reg ap_idle;
reg in_a_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln26_fu_132_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    in_a_TDATA_blk_n;
wire   [63:0] zext_ln26_fu_144_p1;
reg   [4:0] i_fu_56;
wire   [4:0] add_ln26_fu_138_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    in_a_store_data_we0_local;
reg    in_a_store_data_ce0_local;
reg    in_a_store_keep_we0_local;
reg    in_a_store_keep_ce0_local;
reg    in_a_store_strb_we0_local;
reg    in_a_store_strb_ce0_local;
reg    in_a_store_last_we0_local;
reg    in_a_store_last_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_56 = 5'd0;
#0 ap_done_reg = 1'b0;
end

array_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln26_fu_132_p2 == 1'd0)) begin
            i_fu_56 <= add_ln26_fu_138_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_56 <= 5'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_56;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        in_a_TDATA_blk_n = in_a_TVALID;
    end else begin
        in_a_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_TREADY = 1'b1;
    end else begin
        in_a_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_data_ce0_local = 1'b1;
    end else begin
        in_a_store_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_data_we0_local = 1'b1;
    end else begin
        in_a_store_data_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_keep_ce0_local = 1'b1;
    end else begin
        in_a_store_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_keep_we0_local = 1'b1;
    end else begin
        in_a_store_keep_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_last_ce0_local = 1'b1;
    end else begin
        in_a_store_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_last_we0_local = 1'b1;
    end else begin
        in_a_store_last_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_strb_ce0_local = 1'b1;
    end else begin
        in_a_store_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (icmp_ln26_fu_132_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_a_store_strb_we0_local = 1'b1;
    end else begin
        in_a_store_strb_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln26_fu_138_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((icmp_ln26_fu_132_p2 == 1'd0) & (in_a_TVALID == 1'b0)));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln26_fu_132_p2 = ((ap_sig_allocacmp_i_1 == 5'd25) ? 1'b1 : 1'b0);

assign in_a_store_data_address0 = zext_ln26_fu_144_p1;

assign in_a_store_data_ce0 = in_a_store_data_ce0_local;

assign in_a_store_data_d0 = in_a_TDATA;

assign in_a_store_data_we0 = in_a_store_data_we0_local;

assign in_a_store_keep_address0 = zext_ln26_fu_144_p1;

assign in_a_store_keep_ce0 = in_a_store_keep_ce0_local;

assign in_a_store_keep_d0 = in_a_TKEEP;

assign in_a_store_keep_we0 = in_a_store_keep_we0_local;

assign in_a_store_last_address0 = zext_ln26_fu_144_p1;

assign in_a_store_last_ce0 = in_a_store_last_ce0_local;

assign in_a_store_last_d0 = in_a_TLAST;

assign in_a_store_last_we0 = in_a_store_last_we0_local;

assign in_a_store_strb_address0 = zext_ln26_fu_144_p1;

assign in_a_store_strb_ce0 = in_a_store_strb_ce0_local;

assign in_a_store_strb_d0 = in_a_TSTRB;

assign in_a_store_strb_we0 = in_a_store_strb_we0_local;

assign zext_ln26_fu_144_p1 = ap_sig_allocacmp_i_1;

endmodule //array_mult_array_mult_Pipeline_VITIS_LOOP_26_1
