// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_mult_array_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.079540,HLS_SYN_LAT=90,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2910,HLS_SYN_LUT=2169,HLS_VERSION=2024_1}" *)

module array_mult (
        ap_clk,
        ap_rst_n,
        in_a_TDATA,
        in_a_TVALID,
        in_a_TREADY,
        in_a_TKEEP,
        in_a_TSTRB,
        in_a_TLAST,
        result_TDATA,
        result_TVALID,
        result_TREADY,
        result_TKEEP,
        result_TSTRB,
        result_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_DATA_IN_B_AWVALID,
        s_axi_DATA_IN_B_AWREADY,
        s_axi_DATA_IN_B_AWADDR,
        s_axi_DATA_IN_B_WVALID,
        s_axi_DATA_IN_B_WREADY,
        s_axi_DATA_IN_B_WDATA,
        s_axi_DATA_IN_B_WSTRB,
        s_axi_DATA_IN_B_ARVALID,
        s_axi_DATA_IN_B_ARREADY,
        s_axi_DATA_IN_B_ARADDR,
        s_axi_DATA_IN_B_RVALID,
        s_axi_DATA_IN_B_RREADY,
        s_axi_DATA_IN_B_RDATA,
        s_axi_DATA_IN_B_RRESP,
        s_axi_DATA_IN_B_BVALID,
        s_axi_DATA_IN_B_BREADY,
        s_axi_DATA_IN_B_BRESP
);

parameter    ap_ST_fsm_state1 = 31'd1;
parameter    ap_ST_fsm_state2 = 31'd2;
parameter    ap_ST_fsm_state3 = 31'd4;
parameter    ap_ST_fsm_state4 = 31'd8;
parameter    ap_ST_fsm_state5 = 31'd16;
parameter    ap_ST_fsm_state6 = 31'd32;
parameter    ap_ST_fsm_state7 = 31'd64;
parameter    ap_ST_fsm_state8 = 31'd128;
parameter    ap_ST_fsm_state9 = 31'd256;
parameter    ap_ST_fsm_state10 = 31'd512;
parameter    ap_ST_fsm_state11 = 31'd1024;
parameter    ap_ST_fsm_state12 = 31'd2048;
parameter    ap_ST_fsm_state13 = 31'd4096;
parameter    ap_ST_fsm_state14 = 31'd8192;
parameter    ap_ST_fsm_state15 = 31'd16384;
parameter    ap_ST_fsm_state16 = 31'd32768;
parameter    ap_ST_fsm_state17 = 31'd65536;
parameter    ap_ST_fsm_state18 = 31'd131072;
parameter    ap_ST_fsm_state19 = 31'd262144;
parameter    ap_ST_fsm_state20 = 31'd524288;
parameter    ap_ST_fsm_state21 = 31'd1048576;
parameter    ap_ST_fsm_state22 = 31'd2097152;
parameter    ap_ST_fsm_state23 = 31'd4194304;
parameter    ap_ST_fsm_state24 = 31'd8388608;
parameter    ap_ST_fsm_state25 = 31'd16777216;
parameter    ap_ST_fsm_state26 = 31'd33554432;
parameter    ap_ST_fsm_state27 = 31'd67108864;
parameter    ap_ST_fsm_state28 = 31'd134217728;
parameter    ap_ST_fsm_state29 = 31'd268435456;
parameter    ap_ST_fsm_state30 = 31'd536870912;
parameter    ap_ST_fsm_state31 = 31'd1073741824;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_IN_B_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_IN_B_ADDR_WIDTH = 8;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_DATA_IN_B_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_a_TDATA;
input   in_a_TVALID;
output   in_a_TREADY;
input  [3:0] in_a_TKEEP;
input  [3:0] in_a_TSTRB;
input  [0:0] in_a_TLAST;
output  [31:0] result_TDATA;
output   result_TVALID;
input   result_TREADY;
output  [3:0] result_TKEEP;
output  [3:0] result_TSTRB;
output  [0:0] result_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_DATA_IN_B_AWVALID;
output   s_axi_DATA_IN_B_AWREADY;
input  [C_S_AXI_DATA_IN_B_ADDR_WIDTH - 1:0] s_axi_DATA_IN_B_AWADDR;
input   s_axi_DATA_IN_B_WVALID;
output   s_axi_DATA_IN_B_WREADY;
input  [C_S_AXI_DATA_IN_B_DATA_WIDTH - 1:0] s_axi_DATA_IN_B_WDATA;
input  [C_S_AXI_DATA_IN_B_WSTRB_WIDTH - 1:0] s_axi_DATA_IN_B_WSTRB;
input   s_axi_DATA_IN_B_ARVALID;
output   s_axi_DATA_IN_B_ARREADY;
input  [C_S_AXI_DATA_IN_B_ADDR_WIDTH - 1:0] s_axi_DATA_IN_B_ARADDR;
output   s_axi_DATA_IN_B_RVALID;
input   s_axi_DATA_IN_B_RREADY;
output  [C_S_AXI_DATA_IN_B_DATA_WIDTH - 1:0] s_axi_DATA_IN_B_RDATA;
output  [1:0] s_axi_DATA_IN_B_RRESP;
output   s_axi_DATA_IN_B_BVALID;
input   s_axi_DATA_IN_B_BREADY;
output  [1:0] s_axi_DATA_IN_B_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [30:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] in_b_q0;
wire    ap_CS_fsm_state4;
reg   [31:0] in_b_load_reg_427;
wire    ap_CS_fsm_state5;
reg   [31:0] in_b_load_1_reg_437;
wire    ap_CS_fsm_state6;
reg   [31:0] in_b_load_2_reg_447;
wire    ap_CS_fsm_state7;
reg   [31:0] in_b_load_3_reg_457;
wire    ap_CS_fsm_state8;
reg   [31:0] in_b_load_4_reg_467;
wire    ap_CS_fsm_state9;
reg   [31:0] in_b_load_5_reg_477;
wire    ap_CS_fsm_state10;
reg   [31:0] in_b_load_6_reg_487;
wire    ap_CS_fsm_state11;
reg   [31:0] in_b_load_7_reg_497;
wire    ap_CS_fsm_state12;
reg   [31:0] in_b_load_8_reg_507;
wire    ap_CS_fsm_state13;
reg   [31:0] in_b_load_9_reg_517;
wire    ap_CS_fsm_state14;
reg   [31:0] in_b_load_10_reg_527;
wire    ap_CS_fsm_state15;
reg   [31:0] in_b_load_11_reg_537;
wire    ap_CS_fsm_state16;
reg   [31:0] in_b_load_12_reg_547;
wire    ap_CS_fsm_state17;
reg   [31:0] in_b_load_13_reg_557;
wire    ap_CS_fsm_state18;
reg   [31:0] in_b_load_14_reg_567;
wire    ap_CS_fsm_state19;
reg   [31:0] in_b_load_15_reg_577;
wire    ap_CS_fsm_state20;
reg   [31:0] in_b_load_16_reg_587;
wire    ap_CS_fsm_state21;
reg   [31:0] in_b_load_17_reg_597;
wire    ap_CS_fsm_state22;
reg   [31:0] in_b_load_18_reg_607;
wire    ap_CS_fsm_state23;
reg   [31:0] in_b_load_19_reg_617;
wire    ap_CS_fsm_state24;
reg   [31:0] in_b_load_20_reg_627;
wire    ap_CS_fsm_state25;
reg   [31:0] in_b_load_21_reg_637;
wire    ap_CS_fsm_state26;
reg   [31:0] in_b_load_22_reg_647;
wire    ap_CS_fsm_state27;
reg   [31:0] in_b_load_23_reg_657;
wire    ap_CS_fsm_state28;
reg   [31:0] in_b_load_24_reg_667;
wire    ap_CS_fsm_state29;
reg   [4:0] in_a_store_data_address0;
reg    in_a_store_data_ce0;
reg    in_a_store_data_we0;
wire   [31:0] in_a_store_data_q0;
reg    in_a_store_data_ce1;
wire   [31:0] in_a_store_data_q1;
reg   [4:0] in_a_store_keep_address0;
reg    in_a_store_keep_ce0;
reg    in_a_store_keep_we0;
wire   [3:0] in_a_store_keep_q0;
reg   [4:0] in_a_store_strb_address0;
reg    in_a_store_strb_ce0;
reg    in_a_store_strb_we0;
wire   [3:0] in_a_store_strb_q0;
reg   [4:0] in_a_store_last_address0;
reg    in_a_store_last_ce0;
reg    in_a_store_last_we0;
wire   [0:0] in_a_store_last_q0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_idle;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0;
wire   [31:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0;
wire   [3:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0;
wire   [3:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0;
wire   [0:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_idle;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY;
wire   [4:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0;
wire   [4:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0;
wire   [4:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0;
wire   [4:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1;
wire   [31:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA;
wire    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID;
wire   [3:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP;
wire   [3:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB;
wire   [0:0] grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST;
reg    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg;
wire    ap_CS_fsm_state30;
reg    in_b_ce0_local;
reg   [4:0] in_b_address0_local;
wire    ap_CS_fsm_state31;
wire    regslice_both_result_V_data_V_U_apdone_blk;
reg   [30:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
reg    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire    regslice_both_in_a_V_data_V_U_apdone_blk;
wire   [31:0] in_a_TDATA_int_regslice;
wire    in_a_TVALID_int_regslice;
reg    in_a_TREADY_int_regslice;
wire    regslice_both_in_a_V_data_V_U_ack_in;
wire    regslice_both_in_a_V_keep_V_U_apdone_blk;
wire   [3:0] in_a_TKEEP_int_regslice;
wire    regslice_both_in_a_V_keep_V_U_vld_out;
wire    regslice_both_in_a_V_keep_V_U_ack_in;
wire    regslice_both_in_a_V_strb_V_U_apdone_blk;
wire   [3:0] in_a_TSTRB_int_regslice;
wire    regslice_both_in_a_V_strb_V_U_vld_out;
wire    regslice_both_in_a_V_strb_V_U_ack_in;
wire    regslice_both_in_a_V_last_V_U_apdone_blk;
wire   [0:0] in_a_TLAST_int_regslice;
wire    regslice_both_in_a_V_last_V_U_vld_out;
wire    regslice_both_in_a_V_last_V_U_ack_in;
wire    result_TVALID_int_regslice;
wire    result_TREADY_int_regslice;
wire    regslice_both_result_V_data_V_U_vld_out;
wire    regslice_both_result_V_keep_V_U_apdone_blk;
wire    regslice_both_result_V_keep_V_U_ack_in_dummy;
wire    regslice_both_result_V_keep_V_U_vld_out;
wire    regslice_both_result_V_strb_V_U_apdone_blk;
wire    regslice_both_result_V_strb_V_U_ack_in_dummy;
wire    regslice_both_result_V_strb_V_U_vld_out;
wire    regslice_both_result_V_last_V_U_apdone_blk;
wire    regslice_both_result_V_last_V_U_ack_in_dummy;
wire    regslice_both_result_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 31'd1;
#0 grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg = 1'b0;
end

array_mult_in_a_store_data_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_data_address0),
    .ce0(in_a_store_data_ce0),
    .we0(in_a_store_data_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0),
    .q0(in_a_store_data_q0),
    .address1(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1),
    .ce1(in_a_store_data_ce1),
    .q1(in_a_store_data_q1)
);

array_mult_in_a_store_keep_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_keep_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_keep_address0),
    .ce0(in_a_store_keep_ce0),
    .we0(in_a_store_keep_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0),
    .q0(in_a_store_keep_q0)
);

array_mult_in_a_store_keep_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_strb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_strb_address0),
    .ce0(in_a_store_strb_ce0),
    .we0(in_a_store_strb_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0),
    .q0(in_a_store_strb_q0)
);

array_mult_in_a_store_last_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_last_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_last_address0),
    .ce0(in_a_store_last_ce0),
    .we0(in_a_store_last_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0),
    .q0(in_a_store_last_q0)
);

array_mult_array_mult_Pipeline_VITIS_LOOP_26_1 grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start),
    .ap_done(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done),
    .ap_idle(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready),
    .in_a_TVALID(in_a_TVALID_int_regslice),
    .in_a_store_data_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0),
    .in_a_store_data_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0),
    .in_a_store_data_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_d0),
    .in_a_store_keep_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0),
    .in_a_store_keep_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0),
    .in_a_store_keep_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0),
    .in_a_store_keep_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_d0),
    .in_a_store_strb_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0),
    .in_a_store_strb_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0),
    .in_a_store_strb_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0),
    .in_a_store_strb_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_d0),
    .in_a_store_last_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0),
    .in_a_store_last_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0),
    .in_a_store_last_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0),
    .in_a_store_last_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_d0),
    .in_a_TDATA(in_a_TDATA_int_regslice),
    .in_a_TREADY(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY),
    .in_a_TKEEP(in_a_TKEEP_int_regslice),
    .in_a_TSTRB(in_a_TSTRB_int_regslice),
    .in_a_TLAST(in_a_TLAST_int_regslice)
);

array_mult_array_mult_Pipeline_ROWS_LOOP grp_array_mult_Pipeline_ROWS_LOOP_fu_380(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start),
    .ap_done(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done),
    .ap_idle(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready),
    .result_TREADY(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY),
    .in_a_store_last_address0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0),
    .in_a_store_last_ce0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0),
    .in_a_store_last_q0(in_a_store_last_q0),
    .in_a_store_keep_address0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0),
    .in_a_store_keep_ce0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0),
    .in_a_store_keep_q0(in_a_store_keep_q0),
    .in_a_store_strb_address0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0),
    .in_a_store_strb_ce0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0),
    .in_a_store_strb_q0(in_a_store_strb_q0),
    .in_a_store_data_address0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_a_store_data_address1(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address1),
    .in_a_store_data_ce1(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1),
    .in_a_store_data_q1(in_a_store_data_q1),
    .in_b_load_3(in_b_load_3_reg_457),
    .in_b_load_4(in_b_load_4_reg_467),
    .in_b_load(in_b_load_reg_427),
    .in_b_load_2(in_b_load_2_reg_447),
    .in_b_load_1(in_b_load_1_reg_437),
    .result_TDATA(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA),
    .result_TVALID(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID),
    .result_TKEEP(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP),
    .result_TSTRB(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB),
    .result_TLAST(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST),
    .in_b_load_8(in_b_load_8_reg_507),
    .in_b_load_9(in_b_load_9_reg_517),
    .in_b_load_5(in_b_load_5_reg_477),
    .in_b_load_7(in_b_load_7_reg_497),
    .in_b_load_6(in_b_load_6_reg_487),
    .in_b_load_13(in_b_load_13_reg_557),
    .in_b_load_14(in_b_load_14_reg_567),
    .in_b_load_10(in_b_load_10_reg_527),
    .in_b_load_12(in_b_load_12_reg_547),
    .in_b_load_11(in_b_load_11_reg_537),
    .in_b_load_18(in_b_load_18_reg_607),
    .in_b_load_19(in_b_load_19_reg_617),
    .in_b_load_15(in_b_load_15_reg_577),
    .in_b_load_17(in_b_load_17_reg_597),
    .in_b_load_16(in_b_load_16_reg_587),
    .in_b_load_23(in_b_load_23_reg_657),
    .in_b_load_24(in_b_load_24_reg_667),
    .in_b_load_20(in_b_load_20_reg_627),
    .in_b_load_22(in_b_load_22_reg_647),
    .in_b_load_21(in_b_load_21_reg_637)
);

array_mult_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

array_mult_DATA_IN_B_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_DATA_IN_B_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_DATA_IN_B_DATA_WIDTH ))
DATA_IN_B_s_axi_U(
    .AWVALID(s_axi_DATA_IN_B_AWVALID),
    .AWREADY(s_axi_DATA_IN_B_AWREADY),
    .AWADDR(s_axi_DATA_IN_B_AWADDR),
    .WVALID(s_axi_DATA_IN_B_WVALID),
    .WREADY(s_axi_DATA_IN_B_WREADY),
    .WDATA(s_axi_DATA_IN_B_WDATA),
    .WSTRB(s_axi_DATA_IN_B_WSTRB),
    .ARVALID(s_axi_DATA_IN_B_ARVALID),
    .ARREADY(s_axi_DATA_IN_B_ARREADY),
    .ARADDR(s_axi_DATA_IN_B_ARADDR),
    .RVALID(s_axi_DATA_IN_B_RVALID),
    .RREADY(s_axi_DATA_IN_B_RREADY),
    .RDATA(s_axi_DATA_IN_B_RDATA),
    .RRESP(s_axi_DATA_IN_B_RRESP),
    .BVALID(s_axi_DATA_IN_B_BVALID),
    .BREADY(s_axi_DATA_IN_B_BREADY),
    .BRESP(s_axi_DATA_IN_B_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_b_address0(in_b_address0_local),
    .in_b_ce0(in_b_ce0_local),
    .in_b_q0(in_b_q0)
);

array_mult_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_a_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TDATA),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_data_V_U_ack_in),
    .data_out(in_a_TDATA_int_regslice),
    .vld_out(in_a_TVALID_int_regslice),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_data_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_a_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TKEEP),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_keep_V_U_ack_in),
    .data_out(in_a_TKEEP_int_regslice),
    .vld_out(regslice_both_in_a_V_keep_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_keep_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_a_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TSTRB),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_strb_V_U_ack_in),
    .data_out(in_a_TSTRB_int_regslice),
    .vld_out(regslice_both_in_a_V_strb_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_strb_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_a_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TLAST),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_last_V_U_ack_in),
    .data_out(in_a_TLAST_int_regslice),
    .vld_out(regslice_both_in_a_V_last_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_last_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 32 ))
regslice_both_result_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TDATA),
    .vld_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID),
    .ack_in(result_TREADY_int_regslice),
    .data_out(result_TDATA),
    .vld_out(regslice_both_result_V_data_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_data_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TKEEP),
    .vld_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID),
    .ack_in(regslice_both_result_V_keep_V_U_ack_in_dummy),
    .data_out(result_TKEEP),
    .vld_out(regslice_both_result_V_keep_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_keep_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 4 ))
regslice_both_result_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TSTRB),
    .vld_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID),
    .ack_in(regslice_both_result_V_strb_V_U_ack_in_dummy),
    .data_out(result_TSTRB),
    .vld_out(regslice_both_result_V_strb_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_strb_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 1 ))
regslice_both_result_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TLAST),
    .vld_in(grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID),
    .ack_in(regslice_both_result_V_last_V_U_ack_in_dummy),
    .data_out(result_TLAST),
    .vld_out(regslice_both_result_V_last_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state29)) begin
            grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        in_b_load_10_reg_527 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        in_b_load_11_reg_537 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        in_b_load_12_reg_547 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        in_b_load_13_reg_557 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        in_b_load_14_reg_567 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        in_b_load_15_reg_577 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        in_b_load_16_reg_587 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        in_b_load_17_reg_597 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        in_b_load_18_reg_607 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        in_b_load_19_reg_617 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_b_load_1_reg_437 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        in_b_load_20_reg_627 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        in_b_load_21_reg_637 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        in_b_load_22_reg_647 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        in_b_load_23_reg_657 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        in_b_load_24_reg_667 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        in_b_load_2_reg_447 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        in_b_load_3_reg_457 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        in_b_load_4_reg_467 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        in_b_load_5_reg_477 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        in_b_load_6_reg_487 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        in_b_load_7_reg_497 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        in_b_load_8_reg_507 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        in_b_load_9_reg_517 <= in_b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_b_load_reg_427 <= in_b_q0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done == 1'b0)) begin
        ap_ST_fsm_state30_blk = 1'b1;
    end else begin
        ap_ST_fsm_state30_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_result_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_TREADY_int_regslice = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_TREADY;
    end else begin
        in_a_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_address0;
    end else begin
        in_a_store_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_ce0;
    end else begin
        in_a_store_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_data_ce1 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_data_ce1;
    end else begin
        in_a_store_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_data_we0;
    end else begin
        in_a_store_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_keep_address0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_address0;
    end else begin
        in_a_store_keep_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_keep_ce0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_keep_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_ce0;
    end else begin
        in_a_store_keep_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_keep_we0;
    end else begin
        in_a_store_keep_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_last_address0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_address0;
    end else begin
        in_a_store_last_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_last_ce0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_last_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_ce0;
    end else begin
        in_a_store_last_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_last_we0;
    end else begin
        in_a_store_last_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_strb_address0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_address0;
    end else begin
        in_a_store_strb_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        in_a_store_strb_ce0 = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_in_a_store_strb_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_ce0;
    end else begin
        in_a_store_strb_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_in_a_store_strb_we0;
    end else begin
        in_a_store_strb_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        in_b_address0_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        in_b_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        in_b_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        in_b_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        in_b_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        in_b_address0_local = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        in_b_address0_local = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        in_b_address0_local = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        in_b_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        in_b_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_b_address0_local = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        in_b_address0_local = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        in_b_address0_local = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_b_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        in_b_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        in_b_address0_local = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        in_b_address0_local = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        in_b_address0_local = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_b_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_b_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        in_b_address0_local = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_b_address0_local = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        in_b_address0_local = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        in_b_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_b_address0_local = 64'd0;
    end else begin
        in_b_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        in_b_ce0_local = 1'b1;
    end else begin
        in_b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            if (((regslice_both_result_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_ap_start_reg;

assign grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TREADY = (result_TREADY_int_regslice & ap_CS_fsm_state30);

assign grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_364_ap_start_reg;

assign in_a_TREADY = regslice_both_in_a_V_data_V_U_ack_in;

assign result_TVALID = regslice_both_result_V_data_V_U_vld_out;

assign result_TVALID_int_regslice = grp_array_mult_Pipeline_ROWS_LOOP_fu_380_result_TVALID;

endmodule //array_mult
