// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module array_mult_array_mult_Pipeline_ROWS_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        result_TREADY,
        in_a_store_last_address0,
        in_a_store_last_ce0,
        in_a_store_last_q0,
        in_a_store_keep_address0,
        in_a_store_keep_ce0,
        in_a_store_keep_q0,
        in_a_store_strb_address0,
        in_a_store_strb_ce0,
        in_a_store_strb_q0,
        in_a_store_data_address0,
        in_a_store_data_ce0,
        in_a_store_data_q0,
        in_a_store_data_address1,
        in_a_store_data_ce1,
        in_a_store_data_q1,
        in_b_load_3,
        in_b_load_4,
        in_b_load,
        in_b_load_2,
        in_b_load_1,
        result_TDATA,
        result_TVALID,
        result_TKEEP,
        result_TSTRB,
        result_TLAST,
        in_b_load_8,
        in_b_load_9,
        in_b_load_5,
        in_b_load_7,
        in_b_load_6,
        in_b_load_13,
        in_b_load_14,
        in_b_load_10,
        in_b_load_12,
        in_b_load_11,
        in_b_load_18,
        in_b_load_19,
        in_b_load_15,
        in_b_load_17,
        in_b_load_16,
        in_b_load_23,
        in_b_load_24,
        in_b_load_20,
        in_b_load_22,
        in_b_load_21
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   result_TREADY;
output  [4:0] in_a_store_last_address0;
output   in_a_store_last_ce0;
input  [0:0] in_a_store_last_q0;
output  [4:0] in_a_store_keep_address0;
output   in_a_store_keep_ce0;
input  [3:0] in_a_store_keep_q0;
output  [4:0] in_a_store_strb_address0;
output   in_a_store_strb_ce0;
input  [3:0] in_a_store_strb_q0;
output  [4:0] in_a_store_data_address0;
output   in_a_store_data_ce0;
input  [31:0] in_a_store_data_q0;
output  [4:0] in_a_store_data_address1;
output   in_a_store_data_ce1;
input  [31:0] in_a_store_data_q1;
input  [31:0] in_b_load_3;
input  [31:0] in_b_load_4;
input  [31:0] in_b_load;
input  [31:0] in_b_load_2;
input  [31:0] in_b_load_1;
output  [31:0] result_TDATA;
output   result_TVALID;
output  [3:0] result_TKEEP;
output  [3:0] result_TSTRB;
output  [0:0] result_TLAST;
input  [31:0] in_b_load_8;
input  [31:0] in_b_load_9;
input  [31:0] in_b_load_5;
input  [31:0] in_b_load_7;
input  [31:0] in_b_load_6;
input  [31:0] in_b_load_13;
input  [31:0] in_b_load_14;
input  [31:0] in_b_load_10;
input  [31:0] in_b_load_12;
input  [31:0] in_b_load_11;
input  [31:0] in_b_load_18;
input  [31:0] in_b_load_19;
input  [31:0] in_b_load_15;
input  [31:0] in_b_load_17;
input  [31:0] in_b_load_16;
input  [31:0] in_b_load_23;
input  [31:0] in_b_load_24;
input  [31:0] in_b_load_20;
input  [31:0] in_b_load_22;
input  [31:0] in_b_load_21;

reg ap_idle;
reg[31:0] result_TDATA;
reg result_TVALID;
reg[3:0] result_TKEEP;
reg[3:0] result_TSTRB;
reg[0:0] result_TLAST;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
reg    ap_block_state10_pp0_stage4_iter1;
reg    ap_block_pp0_stage4_subdone;
reg   [0:0] icmp_ln30_reg_766;
reg    ap_condition_exit_pp0_iter0_stage4;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    result_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
wire   [31:0] grp_fu_383_p2;
reg   [31:0] reg_403;
reg    ap_block_state9_pp0_stage3_iter1;
reg    ap_block_pp0_stage3_11001;
reg    ap_block_state8_pp0_stage2_iter1;
reg    ap_block_pp0_stage2_11001;
wire   [31:0] grp_fu_387_p2;
reg   [31:0] reg_407;
reg   [31:0] reg_411;
reg    ap_block_pp0_stage4_11001;
reg    ap_block_state12_pp0_stage1_iter2;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] reg_415;
wire   [31:0] grp_fu_391_p2;
reg   [31:0] reg_419;
wire   [31:0] grp_fu_395_p2;
reg   [31:0] reg_423;
wire   [31:0] grp_fu_399_p2;
reg   [31:0] reg_427;
reg    ap_block_state11_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln30_fu_439_p2;
reg   [0:0] icmp_ln30_reg_766_pp0_iter1_reg;
wire   [4:0] trunc_ln40_fu_478_p1;
reg   [4:0] trunc_ln40_reg_770;
reg  signed [31:0] in_a_store_data_load_reg_783;
wire   [63:0] zext_ln40_1_fu_512_p1;
reg   [63:0] zext_ln40_1_reg_802;
reg  signed [31:0] in_a_store_data_load_2_reg_814;
reg  signed [31:0] in_a_store_data_load_3_reg_822;
reg  signed [31:0] in_a_store_data_load_1_reg_835;
reg  signed [31:0] in_a_store_data_load_4_reg_843;
reg   [31:0] mul_ln39_12_reg_851;
reg   [31:0] mul_ln39_17_reg_856;
reg   [31:0] mul_ln39_22_reg_861;
reg   [31:0] mul_ln39_22_reg_861_pp0_iter1_reg;
reg   [31:0] mul_ln39_1_reg_866;
reg   [31:0] mul_ln39_4_reg_871;
reg   [31:0] mul_ln39_6_reg_876;
reg   [31:0] mul_ln39_9_reg_881;
reg   [31:0] mul_ln39_11_reg_886;
wire   [31:0] add_ln39_5_fu_532_p2;
reg   [31:0] add_ln39_5_reg_906;
wire   [31:0] add_ln39_9_fu_543_p2;
reg   [31:0] add_ln39_9_reg_911;
reg   [31:0] mul_ln39_18_reg_916;
reg   [0:0] mult_acc_last_reg_921;
reg   [3:0] mult_acc_keep_reg_926;
reg   [3:0] mult_acc_strb_reg_931;
wire   [31:0] mult_acc_data_1_fu_565_p2;
reg   [31:0] mult_acc_data_1_reg_936;
wire   [31:0] add_ln39_13_fu_575_p2;
reg   [31:0] add_ln39_13_reg_941;
wire   [31:0] add_ln39_17_fu_587_p2;
reg   [31:0] add_ln39_17_reg_946;
wire   [31:0] mult_acc_data_2_fu_597_p2;
reg   [31:0] mult_acc_data_2_reg_951;
wire   [31:0] mult_acc_data_3_fu_607_p2;
reg   [31:0] mult_acc_data_3_reg_956;
wire   [31:0] add_ln39_21_fu_618_p2;
reg   [31:0] add_ln39_21_reg_961;
wire   [31:0] mult_acc_data_4_fu_629_p2;
reg   [31:0] mult_acc_data_4_reg_966;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln40_fu_473_p1;
wire   [63:0] zext_ln39_1_fu_492_p1;
wire   [63:0] zext_ln39_2_fu_502_p1;
wire   [63:0] zext_ln39_fu_522_p1;
reg   [2:0] i_1_fu_122;
wire   [2:0] add_ln30_fu_445_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i;
wire   [31:0] mult_acc_data_fu_554_p2;
reg    ap_block_pp0_stage2_01001;
reg    ap_block_pp0_stage3_01001;
reg    ap_block_pp0_stage4_01001;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
reg    in_a_store_data_ce0_local;
reg   [4:0] in_a_store_data_address0_local;
reg    in_a_store_data_ce1_local;
reg   [4:0] in_a_store_data_address1_local;
reg    in_a_store_last_ce0_local;
reg    in_a_store_keep_ce0_local;
reg    in_a_store_strb_ce0_local;
reg  signed [31:0] grp_fu_383_p0;
reg  signed [31:0] grp_fu_383_p1;
reg  signed [31:0] grp_fu_387_p0;
reg  signed [31:0] grp_fu_387_p1;
reg  signed [31:0] grp_fu_391_p0;
reg  signed [31:0] grp_fu_391_p1;
reg  signed [31:0] grp_fu_395_p0;
reg  signed [31:0] grp_fu_395_p1;
reg  signed [31:0] grp_fu_399_p0;
reg  signed [31:0] grp_fu_399_p1;
wire   [4:0] tmp_fu_455_p3;
wire   [5:0] p_shl_fu_463_p1;
wire   [5:0] zext_ln30_fu_451_p1;
wire   [5:0] mul_i_i250_fu_467_p2;
wire   [4:0] add_ln39_1_fu_487_p2;
wire   [4:0] add_ln39_2_fu_497_p2;
wire   [4:0] add_ln40_fu_507_p2;
wire   [4:0] add_ln39_fu_517_p2;
wire   [31:0] add_ln39_4_fu_527_p2;
wire   [31:0] add_ln39_8_fu_538_p2;
wire   [31:0] add_ln39_3_fu_549_p2;
wire   [31:0] add_ln39_7_fu_560_p2;
wire   [31:0] add_ln39_12_fu_570_p2;
wire   [31:0] add_ln39_16_fu_581_p2;
wire   [31:0] add_ln39_11_fu_592_p2;
wire   [31:0] add_ln39_15_fu_602_p2;
wire   [31:0] add_ln39_20_fu_612_p2;
wire   [31:0] add_ln39_19_fu_624_p2;
reg    grp_fu_383_ce;
reg    grp_fu_387_ce;
reg    grp_fu_391_ce;
reg    grp_fu_395_ce;
reg    grp_fu_399_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter1_stage1;
reg    ap_idle_pp0_0to0;
reg   [4:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_1_fu_122 = 3'd0;
#0 ap_done_reg = 1'b0;
end

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_383_p0),
    .din1(grp_fu_383_p1),
    .ce(grp_fu_383_ce),
    .dout(grp_fu_383_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .ce(grp_fu_387_ce),
    .dout(grp_fu_387_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_391_p0),
    .din1(grp_fu_391_p1),
    .ce(grp_fu_391_ce),
    .dout(grp_fu_391_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_395_p0),
    .din1(grp_fu_395_p1),
    .ce(grp_fu_395_ce),
    .dout(grp_fu_395_p2)
);

array_mult_mul_32s_32s_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_2_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_399_p0),
    .din1(grp_fu_399_p1),
    .ce(grp_fu_399_ce),
    .dout(grp_fu_399_p2)
);

array_mult_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage4),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage4)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln30_fu_439_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_122 <= add_ln30_fu_445_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_122 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln39_13_reg_941 <= add_ln39_13_fu_575_p2;
        add_ln39_17_reg_946 <= add_ln39_17_fu_587_p2;
        mult_acc_data_1_reg_936 <= mult_acc_data_1_fu_565_p2;
        mult_acc_keep_reg_926 <= in_a_store_keep_q0;
        mult_acc_last_reg_921 <= in_a_store_last_q0;
        mult_acc_strb_reg_931 <= in_a_store_strb_q0;
        zext_ln40_1_reg_802[4 : 0] <= zext_ln40_1_fu_512_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln39_21_reg_961 <= add_ln39_21_fu_618_p2;
        mul_ln39_22_reg_861_pp0_iter1_reg <= mul_ln39_22_reg_861;
        mult_acc_data_2_reg_951 <= mult_acc_data_2_fu_597_p2;
        mult_acc_data_3_reg_956 <= mult_acc_data_3_fu_607_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln39_5_reg_906 <= add_ln39_5_fu_532_p2;
        add_ln39_9_reg_911 <= add_ln39_9_fu_543_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln30_reg_766 <= icmp_ln30_fu_439_p2;
        icmp_ln30_reg_766_pp0_iter1_reg <= icmp_ln30_reg_766;
        trunc_ln40_reg_770 <= trunc_ln40_fu_478_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        in_a_store_data_load_1_reg_835 <= in_a_store_data_q1;
        in_a_store_data_load_4_reg_843 <= in_a_store_data_q0;
        mul_ln39_12_reg_851 <= grp_fu_391_p2;
        mul_ln39_17_reg_856 <= grp_fu_395_p2;
        mul_ln39_22_reg_861 <= grp_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        in_a_store_data_load_2_reg_814 <= in_a_store_data_q1;
        in_a_store_data_load_3_reg_822 <= in_a_store_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_data_load_reg_783 <= in_a_store_data_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln39_11_reg_886 <= grp_fu_399_p2;
        mul_ln39_1_reg_866 <= grp_fu_383_p2;
        mul_ln39_4_reg_871 <= grp_fu_387_p2;
        mul_ln39_6_reg_876 <= grp_fu_391_p2;
        mul_ln39_9_reg_881 <= grp_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln39_18_reg_916 <= grp_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mult_acc_data_4_reg_966 <= mult_acc_data_4_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_403 <= grp_fu_383_p2;
        reg_407 <= grp_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_411 <= grp_fu_383_p2;
        reg_415 <= grp_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_419 <= grp_fu_391_p2;
        reg_423 <= grp_fu_395_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_427 <= grp_fu_399_p2;
    end
end

always @ (*) begin
    if (((icmp_ln30_reg_766 == 1'd1) & (1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln30_reg_766_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 3'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_122;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_383_ce = 1'b1;
    end else begin
        grp_fu_383_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_383_p0 = in_a_store_data_load_1_reg_835;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_383_p0 = in_a_store_data_load_2_reg_814;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_383_p0 = in_a_store_data_load_4_reg_843;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_383_p0 = in_a_store_data_load_3_reg_822;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_383_p0 = in_a_store_data_load_reg_783;
    end else begin
        grp_fu_383_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_383_p1 = in_b_load_16;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_383_p1 = in_b_load_12;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_383_p1 = in_b_load_4;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_383_p1 = in_b_load_3;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_383_p1 = in_b_load;
    end else begin
        grp_fu_383_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_387_ce = 1'b1;
    end else begin
        grp_fu_387_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_387_p0 = in_a_store_data_load_3_reg_822;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_387_p0 = in_a_store_data_load_1_reg_835;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_387_p0 = in_a_store_data_load_2_reg_814;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_387_p0 = in_a_store_data_load_reg_783;
    end else begin
        grp_fu_387_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_387_p1 = in_b_load_23;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_387_p1 = in_b_load_11;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_387_p1 = in_b_load_1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_387_p1 = in_b_load_2;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_387_p1 = in_b_load_5;
    end else begin
        grp_fu_387_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_391_ce = 1'b1;
    end else begin
        grp_fu_391_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_391_p0 = in_a_store_data_load_4_reg_843;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_391_p0 = in_a_store_data_load_3_reg_822;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_391_p0 = in_a_store_data_load_reg_783;
    end else begin
        grp_fu_391_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_391_p1 = in_b_load_24;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_391_p1 = in_b_load_18;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_391_p1 = in_b_load_9;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_391_p1 = in_b_load_8;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_391_p1 = in_b_load_10;
    end else begin
        grp_fu_391_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_395_ce = 1'b1;
    end else begin
        grp_fu_395_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_395_p0 = in_a_store_data_load_4_reg_843;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_395_p0 = in_a_store_data_load_1_reg_835;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_395_p0 = in_a_store_data_load_2_reg_814;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_395_p0 = in_a_store_data_load_reg_783;
    end else begin
        grp_fu_395_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_395_p1 = in_b_load_22;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_395_p1 = in_b_load_19;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_395_p1 = in_b_load_6;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_395_p1 = in_b_load_7;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_395_p1 = in_b_load_15;
    end else begin
        grp_fu_395_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_399_ce = 1'b1;
    end else begin
        grp_fu_399_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_399_p0 = in_a_store_data_load_1_reg_835;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_399_p0 = in_a_store_data_load_2_reg_814;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_399_p0 = in_a_store_data_load_4_reg_843;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_399_p0 = in_a_store_data_load_3_reg_822;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_399_p0 = in_a_store_data_load_reg_783;
    end else begin
        grp_fu_399_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_399_p1 = in_b_load_21;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_399_p1 = in_b_load_17;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_399_p1 = in_b_load_14;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_399_p1 = in_b_load_13;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_399_p1 = in_b_load_20;
    end else begin
        grp_fu_399_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_a_store_data_address0_local = zext_ln40_1_fu_512_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_a_store_data_address0_local = zext_ln39_2_fu_502_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            in_a_store_data_address0_local = zext_ln40_fu_473_p1;
        end else begin
            in_a_store_data_address0_local = 'bx;
        end
    end else begin
        in_a_store_data_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_a_store_data_address1_local = zext_ln39_fu_522_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_a_store_data_address1_local = zext_ln39_1_fu_492_p1;
        end else begin
            in_a_store_data_address1_local = 'bx;
        end
    end else begin
        in_a_store_data_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        in_a_store_data_ce0_local = 1'b1;
    end else begin
        in_a_store_data_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        in_a_store_data_ce1_local = 1'b1;
    end else begin
        in_a_store_data_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_keep_ce0_local = 1'b1;
    end else begin
        in_a_store_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_last_ce0_local = 1'b1;
    end else begin
        in_a_store_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        in_a_store_strb_ce0_local = 1'b1;
    end else begin
        in_a_store_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_TDATA = mult_acc_data_4_reg_966;
    end else if (((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_TDATA = mult_acc_data_3_reg_956;
    end else if (((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        result_TDATA = mult_acc_data_2_reg_951;
    end else if (((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        result_TDATA = mult_acc_data_1_reg_936;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        result_TDATA = mult_acc_data_fu_554_p2;
    end else begin
        result_TDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        result_TDATA_blk_n = result_TREADY;
    end else begin
        result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TKEEP = mult_acc_keep_reg_926;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        result_TKEEP = in_a_store_keep_q0;
    end else begin
        result_TKEEP = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_TLAST = mult_acc_last_reg_921;
    end else if ((((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        result_TLAST = 1'd0;
    end else begin
        result_TLAST = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_01001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage4_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TSTRB = mult_acc_strb_reg_931;
    end else if (((1'b0 == ap_block_pp0_stage2_01001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        result_TSTRB = in_a_store_strb_q0;
    end else begin
        result_TSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        result_TVALID = 1'b1;
    end else begin
        result_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((ap_idle_pp0_0to0 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter1_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln30_fu_445_p2 = (ap_sig_allocacmp_i + 3'd1);

assign add_ln39_11_fu_592_p2 = (reg_415 + mul_ln39_12_reg_851);

assign add_ln39_12_fu_570_p2 = (reg_427 + mul_ln39_11_reg_886);

assign add_ln39_13_fu_575_p2 = (add_ln39_12_fu_570_p2 + reg_411);

assign add_ln39_15_fu_602_p2 = (reg_403 + mul_ln39_17_reg_856);

assign add_ln39_16_fu_581_p2 = (reg_419 + reg_423);

assign add_ln39_17_fu_587_p2 = (add_ln39_16_fu_581_p2 + mul_ln39_18_reg_916);

assign add_ln39_19_fu_624_p2 = (reg_427 + mul_ln39_22_reg_861_pp0_iter1_reg);

assign add_ln39_1_fu_487_p2 = (trunc_ln40_reg_770 + 5'd2);

assign add_ln39_20_fu_612_p2 = (reg_407 + reg_419);

assign add_ln39_21_fu_618_p2 = (add_ln39_20_fu_612_p2 + reg_423);

assign add_ln39_2_fu_497_p2 = (trunc_ln40_reg_770 + 5'd3);

assign add_ln39_3_fu_549_p2 = (mul_ln39_4_reg_871 + reg_403);

assign add_ln39_4_fu_527_p2 = (reg_411 + mul_ln39_1_reg_866);

assign add_ln39_5_fu_532_p2 = (add_ln39_4_fu_527_p2 + reg_415);

assign add_ln39_7_fu_560_p2 = (mul_ln39_9_reg_881 + reg_407);

assign add_ln39_8_fu_538_p2 = (reg_419 + mul_ln39_6_reg_876);

assign add_ln39_9_fu_543_p2 = (add_ln39_8_fu_538_p2 + reg_423);

assign add_ln39_fu_517_p2 = (trunc_ln40_reg_770 + 5'd1);

assign add_ln40_fu_507_p2 = (trunc_ln40_reg_770 + 5'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state11_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage0_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state11_pp0_stage0_iter2)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state12_pp0_stage1_iter2));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage1_iter2)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state12_pp0_stage1_iter2)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage2_iter1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state8_pp0_stage2_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state8_pp0_stage2_iter1)));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage3_iter1));
end

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state9_pp0_stage3_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state9_pp0_stage3_iter1)));
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage4_iter1));
end

always @ (*) begin
    ap_block_pp0_stage4_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage4_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((result_TREADY == 1'b0) | (1'b1 == ap_block_state10_pp0_stage4_iter1)));
end

always @ (*) begin
    ap_block_state10_pp0_stage4_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state11_pp0_stage0_iter2 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state12_pp0_stage1_iter2 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp0_stage2_iter1 = (result_TREADY == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage3_iter1 = (result_TREADY == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage4;

assign ap_ready = ap_ready_sig;

assign icmp_ln30_fu_439_p2 = ((ap_sig_allocacmp_i == 3'd5) ? 1'b1 : 1'b0);

assign in_a_store_data_address0 = in_a_store_data_address0_local;

assign in_a_store_data_address1 = in_a_store_data_address1_local;

assign in_a_store_data_ce0 = in_a_store_data_ce0_local;

assign in_a_store_data_ce1 = in_a_store_data_ce1_local;

assign in_a_store_keep_address0 = zext_ln40_1_reg_802;

assign in_a_store_keep_ce0 = in_a_store_keep_ce0_local;

assign in_a_store_last_address0 = zext_ln40_1_reg_802;

assign in_a_store_last_ce0 = in_a_store_last_ce0_local;

assign in_a_store_strb_address0 = zext_ln40_1_reg_802;

assign in_a_store_strb_ce0 = in_a_store_strb_ce0_local;

assign mul_i_i250_fu_467_p2 = (p_shl_fu_463_p1 + zext_ln30_fu_451_p1);

assign mult_acc_data_1_fu_565_p2 = (add_ln39_9_reg_911 + add_ln39_7_fu_560_p2);

assign mult_acc_data_2_fu_597_p2 = (add_ln39_13_reg_941 + add_ln39_11_fu_592_p2);

assign mult_acc_data_3_fu_607_p2 = (add_ln39_17_reg_946 + add_ln39_15_fu_602_p2);

assign mult_acc_data_4_fu_629_p2 = (add_ln39_21_reg_961 + add_ln39_19_fu_624_p2);

assign mult_acc_data_fu_554_p2 = (add_ln39_5_reg_906 + add_ln39_3_fu_549_p2);

assign p_shl_fu_463_p1 = tmp_fu_455_p3;

assign tmp_fu_455_p3 = {{ap_sig_allocacmp_i}, {2'd0}};

assign trunc_ln40_fu_478_p1 = mul_i_i250_fu_467_p2[4:0];

assign zext_ln30_fu_451_p1 = ap_sig_allocacmp_i;

assign zext_ln39_1_fu_492_p1 = add_ln39_1_fu_487_p2;

assign zext_ln39_2_fu_502_p1 = add_ln39_2_fu_497_p2;

assign zext_ln39_fu_522_p1 = add_ln39_fu_517_p2;

assign zext_ln40_1_fu_512_p1 = add_ln40_fu_507_p2;

assign zext_ln40_fu_473_p1 = mul_i_i250_fu_467_p2;

always @ (posedge ap_clk) begin
    zext_ln40_1_reg_802[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
end

endmodule //array_mult_array_mult_Pipeline_ROWS_LOOP
