// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="array_mult_array_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.146000,HLS_SYN_LAT=610,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=847,HLS_SYN_LUT=2539,HLS_VERSION=2024_1}" *)

module array_mult (
        ap_clk,
        ap_rst_n,
        in_a_TDATA,
        in_a_TVALID,
        in_a_TREADY,
        in_a_TKEEP,
        in_a_TSTRB,
        in_a_TLAST,
        result_TDATA,
        result_TVALID,
        result_TREADY,
        result_TKEEP,
        result_TSTRB,
        result_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt,
        s_axi_DATA_IN_B_AWVALID,
        s_axi_DATA_IN_B_AWREADY,
        s_axi_DATA_IN_B_AWADDR,
        s_axi_DATA_IN_B_WVALID,
        s_axi_DATA_IN_B_WREADY,
        s_axi_DATA_IN_B_WDATA,
        s_axi_DATA_IN_B_WSTRB,
        s_axi_DATA_IN_B_ARVALID,
        s_axi_DATA_IN_B_ARREADY,
        s_axi_DATA_IN_B_ARADDR,
        s_axi_DATA_IN_B_RVALID,
        s_axi_DATA_IN_B_RREADY,
        s_axi_DATA_IN_B_RDATA,
        s_axi_DATA_IN_B_RRESP,
        s_axi_DATA_IN_B_BVALID,
        s_axi_DATA_IN_B_BREADY,
        s_axi_DATA_IN_B_BRESP
);

parameter    ap_ST_fsm_state1 = 44'd1;
parameter    ap_ST_fsm_state2 = 44'd2;
parameter    ap_ST_fsm_state3 = 44'd4;
parameter    ap_ST_fsm_state4 = 44'd8;
parameter    ap_ST_fsm_state5 = 44'd16;
parameter    ap_ST_fsm_state6 = 44'd32;
parameter    ap_ST_fsm_state7 = 44'd64;
parameter    ap_ST_fsm_state8 = 44'd128;
parameter    ap_ST_fsm_state9 = 44'd256;
parameter    ap_ST_fsm_state10 = 44'd512;
parameter    ap_ST_fsm_state11 = 44'd1024;
parameter    ap_ST_fsm_state12 = 44'd2048;
parameter    ap_ST_fsm_state13 = 44'd4096;
parameter    ap_ST_fsm_state14 = 44'd8192;
parameter    ap_ST_fsm_state15 = 44'd16384;
parameter    ap_ST_fsm_state16 = 44'd32768;
parameter    ap_ST_fsm_state17 = 44'd65536;
parameter    ap_ST_fsm_state18 = 44'd131072;
parameter    ap_ST_fsm_state19 = 44'd262144;
parameter    ap_ST_fsm_state20 = 44'd524288;
parameter    ap_ST_fsm_state21 = 44'd1048576;
parameter    ap_ST_fsm_state22 = 44'd2097152;
parameter    ap_ST_fsm_state23 = 44'd4194304;
parameter    ap_ST_fsm_state24 = 44'd8388608;
parameter    ap_ST_fsm_state25 = 44'd16777216;
parameter    ap_ST_fsm_state26 = 44'd33554432;
parameter    ap_ST_fsm_state27 = 44'd67108864;
parameter    ap_ST_fsm_state28 = 44'd134217728;
parameter    ap_ST_fsm_state29 = 44'd268435456;
parameter    ap_ST_fsm_state30 = 44'd536870912;
parameter    ap_ST_fsm_state31 = 44'd1073741824;
parameter    ap_ST_fsm_state32 = 44'd2147483648;
parameter    ap_ST_fsm_state33 = 44'd4294967296;
parameter    ap_ST_fsm_state34 = 44'd8589934592;
parameter    ap_ST_fsm_state35 = 44'd17179869184;
parameter    ap_ST_fsm_state36 = 44'd34359738368;
parameter    ap_ST_fsm_state37 = 44'd68719476736;
parameter    ap_ST_fsm_state38 = 44'd137438953472;
parameter    ap_ST_fsm_state39 = 44'd274877906944;
parameter    ap_ST_fsm_state40 = 44'd549755813888;
parameter    ap_ST_fsm_state41 = 44'd1099511627776;
parameter    ap_ST_fsm_state42 = 44'd2199023255552;
parameter    ap_ST_fsm_state43 = 44'd4398046511104;
parameter    ap_ST_fsm_state44 = 44'd8796093022208;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_IN_B_DATA_WIDTH = 32;
parameter    C_S_AXI_DATA_IN_B_ADDR_WIDTH = 7;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_DATA_IN_B_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [15:0] in_a_TDATA;
input   in_a_TVALID;
output   in_a_TREADY;
input  [1:0] in_a_TKEEP;
input  [1:0] in_a_TSTRB;
input  [0:0] in_a_TLAST;
output  [15:0] result_TDATA;
output   result_TVALID;
input   result_TREADY;
output  [1:0] result_TKEEP;
output  [1:0] result_TSTRB;
output  [0:0] result_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;
input   s_axi_DATA_IN_B_AWVALID;
output   s_axi_DATA_IN_B_AWREADY;
input  [C_S_AXI_DATA_IN_B_ADDR_WIDTH - 1:0] s_axi_DATA_IN_B_AWADDR;
input   s_axi_DATA_IN_B_WVALID;
output   s_axi_DATA_IN_B_WREADY;
input  [C_S_AXI_DATA_IN_B_DATA_WIDTH - 1:0] s_axi_DATA_IN_B_WDATA;
input  [C_S_AXI_DATA_IN_B_WSTRB_WIDTH - 1:0] s_axi_DATA_IN_B_WSTRB;
input   s_axi_DATA_IN_B_ARVALID;
output   s_axi_DATA_IN_B_ARREADY;
input  [C_S_AXI_DATA_IN_B_ADDR_WIDTH - 1:0] s_axi_DATA_IN_B_ARADDR;
output   s_axi_DATA_IN_B_RVALID;
input   s_axi_DATA_IN_B_RREADY;
output  [C_S_AXI_DATA_IN_B_DATA_WIDTH - 1:0] s_axi_DATA_IN_B_RDATA;
output  [1:0] s_axi_DATA_IN_B_RRESP;
output   s_axi_DATA_IN_B_BVALID;
input   s_axi_DATA_IN_B_BREADY;
output  [1:0] s_axi_DATA_IN_B_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [43:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [4:0] in_b_address0;
reg    in_b_ce0;
wire   [15:0] in_b_q0;
reg    result_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg   [1:0] reg_468;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state37;
reg   [1:0] reg_473;
wire    ap_CS_fsm_state4;
reg   [0:0] in_a_store_last_load_reg_980;
wire   [4:0] empty_19_fu_486_p1;
reg   [4:0] empty_19_reg_988;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln32_fu_509_p2;
reg   [0:0] icmp_ln32_reg_993;
wire   [0:0] mult_acc_last_fu_524_p2;
wire   [4:0] or_ln_fu_539_p3;
reg   [4:0] or_ln_reg_1005;
reg   [0:0] in_a_store_last_load_1_reg_1035;
wire   [4:0] empty_20_fu_570_p1;
reg   [4:0] empty_20_reg_1043;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln32_1_fu_593_p2;
reg   [0:0] icmp_ln32_1_reg_1048;
wire   [0:0] mult_acc_last_1_fu_608_p2;
wire   [4:0] or_ln36_1_fu_623_p3;
reg   [4:0] or_ln36_1_reg_1060;
reg   [0:0] in_a_store_last_load_2_reg_1090;
wire   [4:0] empty_21_fu_654_p1;
reg   [4:0] empty_21_reg_1098;
wire    ap_CS_fsm_state22;
wire   [0:0] icmp_ln32_2_fu_677_p2;
reg   [0:0] icmp_ln32_2_reg_1103;
wire   [0:0] mult_acc_last_2_fu_692_p2;
wire   [4:0] or_ln36_2_fu_707_p3;
reg   [4:0] or_ln36_2_reg_1115;
reg   [0:0] in_a_store_last_load_3_reg_1145;
wire   [4:0] empty_22_fu_738_p1;
reg   [4:0] empty_22_reg_1153;
wire    ap_CS_fsm_state30;
wire   [0:0] mult_acc_last_3_fu_749_p2;
reg   [0:0] mult_acc_last_3_reg_1158;
wire   [0:0] icmp_ln32_3_fu_772_p2;
reg   [0:0] icmp_ln32_3_reg_1163;
wire   [4:0] or_ln36_3_fu_791_p3;
reg   [4:0] or_ln36_3_reg_1170;
reg   [0:0] in_a_store_last_load_4_reg_1200;
wire   [4:0] empty_23_fu_822_p1;
reg   [4:0] empty_23_reg_1208;
wire    ap_CS_fsm_state38;
wire   [0:0] icmp_ln32_4_fu_845_p2;
reg   [0:0] icmp_ln32_4_reg_1213;
wire   [0:0] mult_acc_last_4_fu_860_p2;
wire   [4:0] or_ln36_4_fu_875_p3;
reg   [4:0] or_ln36_4_reg_1225;
reg   [4:0] in_a_store_data_address0;
reg    in_a_store_data_ce0;
reg    in_a_store_data_we0;
wire   [15:0] in_a_store_data_q0;
reg   [4:0] in_a_store_keep_address0;
reg    in_a_store_keep_ce0;
reg    in_a_store_keep_we0;
wire   [1:0] in_a_store_keep_q0;
reg   [4:0] in_a_store_strb_address0;
reg    in_a_store_strb_ce0;
reg    in_a_store_strb_we0;
wire   [1:0] in_a_store_strb_q0;
reg   [4:0] in_a_store_last_address0;
reg    in_a_store_last_ce0;
reg    in_a_store_last_we0;
wire   [0:0] in_a_store_last_q0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_done;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_idle;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_we0;
wire   [15:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_we0;
wire   [1:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_we0;
wire   [1:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_d0;
wire   [4:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_address0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_ce0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_we0;
wire   [0:0] grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_d0;
wire    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_TREADY;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_mult_acc_data_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_mult_acc_data_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_mult_acc_data_2_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_mult_acc_data_2_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_mult_acc_data_4_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_mult_acc_data_4_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_mult_acc_data_6_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_mult_acc_data_6_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_mult_acc_data_8_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_mult_acc_data_8_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_mult_acc_data_10_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_mult_acc_data_10_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_mult_acc_data_12_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_mult_acc_data_12_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_mult_acc_data_14_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_mult_acc_data_14_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_mult_acc_data_16_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_mult_acc_data_16_out_ap_vld;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_done;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_idle;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_ready;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_ce0;
wire   [4:0] grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_address0;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_ce0;
wire   [15:0] grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_mult_acc_data_18_out;
wire    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_mult_acc_data_18_out_ap_vld;
reg    grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg;
wire    ap_CS_fsm_state18;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg;
wire    ap_CS_fsm_state23;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg;
wire    ap_CS_fsm_state26;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg;
wire    ap_CS_fsm_state31;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg;
wire    ap_CS_fsm_state34;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg;
wire    ap_CS_fsm_state39;
reg    grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg;
wire    regslice_both_result_V_data_V_U_apdone_blk;
reg    ap_block_state41_ignore_call2;
wire    ap_CS_fsm_state42;
reg   [15:0] j_fu_134;
wire   [15:0] j_16_fu_548_p2;
reg   [15:0] j_2_fu_194;
wire   [15:0] j_18_fu_632_p2;
reg   [15:0] j_5_fu_198;
wire   [15:0] j_20_fu_716_p2;
reg   [15:0] j_8_fu_202;
wire   [15:0] j_23_fu_800_p2;
reg   [15:0] j_11_fu_206;
wire   [15:0] j_26_fu_884_p2;
reg    ap_block_state41;
reg    in_a_store_last_ce0_local;
reg   [4:0] in_a_store_last_address0_local;
reg    in_a_store_keep_ce0_local;
reg   [4:0] in_a_store_keep_address0_local;
reg    in_a_store_strb_ce0_local;
reg   [4:0] in_a_store_strb_address0_local;
wire   [14:0] tmp_fu_491_p4;
wire   [15:0] j_1_fu_501_p3;
wire   [0:0] cmp_i_i_0_fu_519_p2;
wire   [3:0] tmp_1_fu_530_p4;
wire   [14:0] tmp_2_fu_575_p4;
wire   [15:0] j_4_fu_585_p3;
wire   [0:0] cmp_i_i_1_0_fu_603_p2;
wire   [3:0] tmp_3_fu_614_p4;
wire   [14:0] tmp_4_fu_659_p4;
wire   [15:0] j_7_fu_669_p3;
wire   [0:0] cmp_i_i_2_0_fu_687_p2;
wire   [3:0] tmp_5_fu_698_p4;
wire   [0:0] cmp_i_i_3_0_fu_743_p2;
wire   [14:0] tmp_6_fu_754_p4;
wire   [15:0] j_22_fu_764_p3;
wire   [3:0] tmp_7_fu_782_p4;
wire   [14:0] tmp_8_fu_827_p4;
wire   [15:0] j_25_fu_837_p3;
wire   [0:0] cmp_i_i_4_0_fu_855_p2;
wire   [3:0] tmp_9_fu_866_p4;
reg   [43:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
reg    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
reg    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
reg    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
reg    ap_ST_fsm_state35_blk;
reg    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
reg    ap_ST_fsm_state41_blk;
reg    ap_ST_fsm_state42_blk;
reg    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    regslice_both_in_a_V_data_V_U_apdone_blk;
wire   [15:0] in_a_TDATA_int_regslice;
wire    in_a_TVALID_int_regslice;
reg    in_a_TREADY_int_regslice;
wire    regslice_both_in_a_V_data_V_U_ack_in;
wire    regslice_both_in_a_V_keep_V_U_apdone_blk;
wire   [1:0] in_a_TKEEP_int_regslice;
wire    regslice_both_in_a_V_keep_V_U_vld_out;
wire    regslice_both_in_a_V_keep_V_U_ack_in;
wire    regslice_both_in_a_V_strb_V_U_apdone_blk;
wire   [1:0] in_a_TSTRB_int_regslice;
wire    regslice_both_in_a_V_strb_V_U_vld_out;
wire    regslice_both_in_a_V_strb_V_U_ack_in;
wire    regslice_both_in_a_V_last_V_U_apdone_blk;
wire   [0:0] in_a_TLAST_int_regslice;
wire    regslice_both_in_a_V_last_V_U_vld_out;
wire    regslice_both_in_a_V_last_V_U_ack_in;
reg   [15:0] result_TDATA_int_regslice;
reg    result_TVALID_int_regslice;
wire    result_TREADY_int_regslice;
wire    regslice_both_result_V_data_V_U_vld_out;
wire    regslice_both_result_V_keep_V_U_apdone_blk;
wire    regslice_both_result_V_keep_V_U_ack_in_dummy;
wire    regslice_both_result_V_keep_V_U_vld_out;
wire    regslice_both_result_V_strb_V_U_apdone_blk;
wire    regslice_both_result_V_strb_V_U_ack_in_dummy;
wire    regslice_both_result_V_strb_V_U_vld_out;
wire    regslice_both_result_V_last_V_U_apdone_blk;
reg   [0:0] result_TLAST_int_regslice;
wire    regslice_both_result_V_last_V_U_ack_in_dummy;
wire    regslice_both_result_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 44'd1;
#0 grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg = 1'b0;
#0 grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg = 1'b0;
#0 j_fu_134 = 16'd0;
#0 j_2_fu_194 = 16'd0;
#0 j_5_fu_198 = 16'd0;
#0 j_8_fu_202 = 16'd0;
#0 j_11_fu_206 = 16'd0;
end

array_mult_in_a_store_data_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_data_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_data_address0),
    .ce0(in_a_store_data_ce0),
    .we0(in_a_store_data_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_d0),
    .q0(in_a_store_data_q0)
);

array_mult_in_a_store_keep_RAM_AUTO_1R1W #(
    .DataWidth( 2 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_keep_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_keep_address0),
    .ce0(in_a_store_keep_ce0),
    .we0(in_a_store_keep_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_d0),
    .q0(in_a_store_keep_q0)
);

array_mult_in_a_store_keep_RAM_AUTO_1R1W #(
    .DataWidth( 2 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_strb_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_strb_address0),
    .ce0(in_a_store_strb_ce0),
    .we0(in_a_store_strb_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_d0),
    .q0(in_a_store_strb_q0)
);

array_mult_in_a_store_last_RAM_AUTO_1R1W #(
    .DataWidth( 1 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
in_a_store_last_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(in_a_store_last_address0),
    .ce0(in_a_store_last_ce0),
    .we0(in_a_store_last_we0),
    .d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_d0),
    .q0(in_a_store_last_q0)
);

array_mult_array_mult_Pipeline_VITIS_LOOP_26_1 grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start),
    .ap_done(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_done),
    .ap_idle(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_ready),
    .in_a_TVALID(in_a_TVALID_int_regslice),
    .in_a_store_data_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_ce0),
    .in_a_store_data_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_we0),
    .in_a_store_data_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_d0),
    .in_a_store_keep_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_address0),
    .in_a_store_keep_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_ce0),
    .in_a_store_keep_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_we0),
    .in_a_store_keep_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_d0),
    .in_a_store_strb_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_address0),
    .in_a_store_strb_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_ce0),
    .in_a_store_strb_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_we0),
    .in_a_store_strb_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_d0),
    .in_a_store_last_address0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_address0),
    .in_a_store_last_ce0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_ce0),
    .in_a_store_last_we0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_we0),
    .in_a_store_last_d0(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_d0),
    .in_a_TDATA(in_a_TDATA_int_regslice),
    .in_a_TREADY(grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_TREADY),
    .in_a_TKEEP(in_a_TKEEP_int_regslice),
    .in_a_TSTRB(in_a_TSTRB_int_regslice),
    .in_a_TLAST(in_a_TLAST_int_regslice)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_ready),
    .j(empty_19_reg_988),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_out(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_mult_acc_data_out),
    .mult_acc_data_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_mult_acc_data_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP1 grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_ready),
    .or_ln(or_ln_reg_1005),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_2_out(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_mult_acc_data_2_out),
    .mult_acc_data_2_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_mult_acc_data_2_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP2 grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_ready),
    .j_2(empty_20_reg_1043),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_4_out(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_mult_acc_data_4_out),
    .mult_acc_data_4_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_mult_acc_data_4_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP3 grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_ready),
    .or_ln36_1(or_ln36_1_reg_1060),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_6_out(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_mult_acc_data_6_out),
    .mult_acc_data_6_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_mult_acc_data_6_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP4 grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_ready),
    .j_5(empty_21_reg_1098),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_8_out(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_mult_acc_data_8_out),
    .mult_acc_data_8_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_mult_acc_data_8_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP5 grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_ready),
    .or_ln36_2(or_ln36_2_reg_1115),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_10_out(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_mult_acc_data_10_out),
    .mult_acc_data_10_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_mult_acc_data_10_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP6 grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_ready),
    .j_8(empty_22_reg_1153),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_12_out(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_mult_acc_data_12_out),
    .mult_acc_data_12_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_mult_acc_data_12_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP7 grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_ready),
    .or_ln36_3(or_ln36_3_reg_1170),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_14_out(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_mult_acc_data_14_out),
    .mult_acc_data_14_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_mult_acc_data_14_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP8 grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_ready),
    .j_11(empty_23_reg_1208),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_16_out(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_mult_acc_data_16_out),
    .mult_acc_data_16_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_mult_acc_data_16_out_ap_vld)
);

array_mult_array_mult_Pipeline_MULT_ACC_LOOP9 grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start),
    .ap_done(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_done),
    .ap_idle(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_idle),
    .ap_ready(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_ready),
    .or_ln36_4(or_ln36_4_reg_1225),
    .in_a_store_data_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_address0),
    .in_a_store_data_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_ce0),
    .in_a_store_data_q0(in_a_store_data_q0),
    .in_b_address0(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_address0),
    .in_b_ce0(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_ce0),
    .in_b_q0(in_b_q0),
    .mult_acc_data_18_out(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_mult_acc_data_18_out),
    .mult_acc_data_18_out_ap_vld(grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_mult_acc_data_18_out_ap_vld)
);

array_mult_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

array_mult_DATA_IN_B_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_DATA_IN_B_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_DATA_IN_B_DATA_WIDTH ))
DATA_IN_B_s_axi_U(
    .AWVALID(s_axi_DATA_IN_B_AWVALID),
    .AWREADY(s_axi_DATA_IN_B_AWREADY),
    .AWADDR(s_axi_DATA_IN_B_AWADDR),
    .WVALID(s_axi_DATA_IN_B_WVALID),
    .WREADY(s_axi_DATA_IN_B_WREADY),
    .WDATA(s_axi_DATA_IN_B_WDATA),
    .WSTRB(s_axi_DATA_IN_B_WSTRB),
    .ARVALID(s_axi_DATA_IN_B_ARVALID),
    .ARREADY(s_axi_DATA_IN_B_ARREADY),
    .ARADDR(s_axi_DATA_IN_B_ARADDR),
    .RVALID(s_axi_DATA_IN_B_RVALID),
    .RREADY(s_axi_DATA_IN_B_RREADY),
    .RDATA(s_axi_DATA_IN_B_RDATA),
    .RRESP(s_axi_DATA_IN_B_RRESP),
    .BVALID(s_axi_DATA_IN_B_BVALID),
    .BREADY(s_axi_DATA_IN_B_BREADY),
    .BRESP(s_axi_DATA_IN_B_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_b_address0(in_b_address0),
    .in_b_ce0(in_b_ce0),
    .in_b_q0(in_b_q0)
);

array_mult_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_a_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TDATA),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_data_V_U_ack_in),
    .data_out(in_a_TDATA_int_regslice),
    .vld_out(in_a_TVALID_int_regslice),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_data_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_a_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TKEEP),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_keep_V_U_ack_in),
    .data_out(in_a_TKEEP_int_regslice),
    .vld_out(regslice_both_in_a_V_keep_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_keep_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_a_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TSTRB),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_strb_V_U_ack_in),
    .data_out(in_a_TSTRB_int_regslice),
    .vld_out(regslice_both_in_a_V_strb_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_strb_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_a_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_a_TLAST),
    .vld_in(in_a_TVALID),
    .ack_in(regslice_both_in_a_V_last_V_U_ack_in),
    .data_out(in_a_TLAST_int_regslice),
    .vld_out(regslice_both_in_a_V_last_V_U_vld_out),
    .ack_out(in_a_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_a_V_last_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 16 ))
regslice_both_result_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(result_TDATA_int_regslice),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(result_TREADY_int_regslice),
    .data_out(result_TDATA),
    .vld_out(regslice_both_result_V_data_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_data_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 2 ))
regslice_both_result_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(reg_468),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_keep_V_U_ack_in_dummy),
    .data_out(result_TKEEP),
    .vld_out(regslice_both_result_V_keep_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_keep_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 2 ))
regslice_both_result_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(reg_473),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_strb_V_U_ack_in_dummy),
    .data_out(result_TSTRB),
    .vld_out(regslice_both_result_V_strb_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_strb_V_U_apdone_blk)
);

array_mult_regslice_both #(
    .DataWidth( 1 ))
regslice_both_result_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(result_TLAST_int_regslice),
    .vld_in(result_TVALID_int_regslice),
    .ack_in(regslice_both_result_V_last_V_U_ack_in_dummy),
    .data_out(result_TLAST),
    .vld_out(regslice_both_result_V_last_V_U_vld_out),
    .ack_out(result_TREADY),
    .apdone_blk(regslice_both_result_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_reg_993 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1))) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_1_reg_1048 == 1'd1) & (1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1))) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_2_reg_1103 == 1'd1) & (1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1))) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state30)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_3_reg_1163 == 1'd1) & (1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1))) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state38)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg <= 1'b0;
    end else begin
        if ((~((1'b1 == ap_block_state41_ignore_call2) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg <= 1'b1;
        end else if ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_ready == 1'b1)) begin
            grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_3_reg_1163 == 1'd0) & (1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1))) begin
        j_11_fu_206 <= 16'd0;
    end else if ((~((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        j_11_fu_206 <= j_26_fu_884_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((result_TREADY_int_regslice == 1'b1)) begin
        if (((icmp_ln32_reg_993 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
            j_2_fu_194 <= 16'd0;
        end else if (((icmp_ln32_1_reg_1048 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
            j_2_fu_194 <= j_18_fu_632_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((result_TREADY_int_regslice == 1'b1)) begin
        if (((icmp_ln32_1_reg_1048 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
            j_5_fu_198 <= 16'd0;
        end else if (((icmp_ln32_2_reg_1103 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
            j_5_fu_198 <= j_20_fu_716_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((result_TREADY_int_regslice == 1'b1)) begin
        if (((icmp_ln32_2_reg_1103 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
            j_8_fu_202 <= 16'd0;
        end else if (((icmp_ln32_3_reg_1163 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
            j_8_fu_202 <= j_23_fu_800_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_fu_134 <= 16'd0;
    end else if (((icmp_ln32_reg_993 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1))) begin
        j_fu_134 <= j_16_fu_548_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        empty_19_reg_988 <= empty_19_fu_486_p1;
        icmp_ln32_reg_993 <= icmp_ln32_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        empty_20_reg_1043 <= empty_20_fu_570_p1;
        icmp_ln32_1_reg_1048 <= icmp_ln32_1_fu_593_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        empty_21_reg_1098 <= empty_21_fu_654_p1;
        icmp_ln32_2_reg_1103 <= icmp_ln32_2_fu_677_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        empty_22_reg_1153 <= empty_22_fu_738_p1;
        icmp_ln32_3_reg_1163 <= icmp_ln32_3_fu_772_p2;
        mult_acc_last_3_reg_1158 <= mult_acc_last_3_fu_749_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        empty_23_reg_1208 <= empty_23_fu_822_p1;
        icmp_ln32_4_reg_1213 <= icmp_ln32_4_fu_845_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        in_a_store_last_load_1_reg_1035 <= in_a_store_last_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        in_a_store_last_load_2_reg_1090 <= in_a_store_last_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        in_a_store_last_load_3_reg_1145 <= in_a_store_last_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        in_a_store_last_load_4_reg_1200 <= in_a_store_last_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_a_store_last_load_reg_980 <= in_a_store_last_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        or_ln36_1_reg_1060[4 : 1] <= or_ln36_1_fu_623_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        or_ln36_2_reg_1115[4 : 1] <= or_ln36_2_fu_707_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        or_ln36_3_reg_1170[4 : 1] <= or_ln36_3_fu_791_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        or_ln36_4_reg_1225[4 : 1] <= or_ln36_4_fu_875_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        or_ln_reg_1005[4 : 1] <= or_ln_fu_539_p3[4 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_468 <= in_a_store_keep_q0;
        reg_473 <= in_a_store_strb_q0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state24_blk = 1'b1;
    end else begin
        ap_ST_fsm_state24_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_done == 1'b0)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state28_blk = 1'b1;
    end else begin
        ap_ST_fsm_state28_blk = 1'b0;
    end
end

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_done == 1'b0)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state33_blk = 1'b1;
    end else begin
        ap_ST_fsm_state33_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state35_blk = 1'b1;
    end else begin
        ap_ST_fsm_state35_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state36_blk = 1'b1;
    end else begin
        ap_ST_fsm_state36_blk = 1'b0;
    end
end

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_done == 1'b0)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0))) begin
        ap_ST_fsm_state41_blk = 1'b1;
    end else begin
        ap_ST_fsm_state41_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_done == 1'b0)) begin
        ap_ST_fsm_state42_blk = 1'b1;
    end else begin
        ap_ST_fsm_state42_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state43_blk = 1'b1;
    end else begin
        ap_ST_fsm_state43_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_TREADY_int_regslice = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_TREADY;
    end else begin
        in_a_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_address0;
    end else begin
        in_a_store_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_a_store_data_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_ce0;
    end else begin
        in_a_store_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_data_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_data_we0;
    end else begin
        in_a_store_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_address0;
    end else begin
        in_a_store_keep_address0 = in_a_store_keep_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        in_a_store_keep_address0_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        in_a_store_keep_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        in_a_store_keep_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_a_store_keep_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_a_store_keep_address0_local = 64'd4;
    end else begin
        in_a_store_keep_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_ce0;
    end else begin
        in_a_store_keep_ce0 = in_a_store_keep_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1)))) begin
        in_a_store_keep_ce0_local = 1'b1;
    end else begin
        in_a_store_keep_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_keep_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_keep_we0;
    end else begin
        in_a_store_keep_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_address0;
    end else begin
        in_a_store_last_address0 = in_a_store_last_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        in_a_store_last_address0_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        in_a_store_last_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        in_a_store_last_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_a_store_last_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_a_store_last_address0_local = 64'd4;
    end else begin
        in_a_store_last_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_ce0;
    end else begin
        in_a_store_last_ce0 = in_a_store_last_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1)))) begin
        in_a_store_last_ce0_local = 1'b1;
    end else begin
        in_a_store_last_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_last_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_last_we0;
    end else begin
        in_a_store_last_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_address0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_address0;
    end else begin
        in_a_store_strb_address0 = in_a_store_strb_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        in_a_store_strb_address0_local = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        in_a_store_strb_address0_local = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        in_a_store_strb_address0_local = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        in_a_store_strb_address0_local = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        in_a_store_strb_address0_local = 64'd4;
    end else begin
        in_a_store_strb_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_ce0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_ce0;
    end else begin
        in_a_store_strb_ce0 = in_a_store_strb_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1)))) begin
        in_a_store_strb_ce0_local = 1'b1;
    end else begin
        in_a_store_strb_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_a_store_strb_we0 = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_in_a_store_strb_we0;
    end else begin
        in_a_store_strb_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_b_address0 = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_address0;
    end else begin
        in_b_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_in_b_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        in_b_ce0 = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_in_b_ce0;
    end else begin
        in_b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state17))) begin
        result_TDATA_blk_n = result_TREADY_int_regslice;
    end else begin
        result_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((result_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state43)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_mult_acc_data_18_out;
        end else if ((1'b1 == ap_CS_fsm_state40)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_mult_acc_data_16_out;
        end else if ((1'b1 == ap_CS_fsm_state35)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_mult_acc_data_14_out;
        end else if ((1'b1 == ap_CS_fsm_state32)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_mult_acc_data_12_out;
        end else if ((1'b1 == ap_CS_fsm_state27)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_mult_acc_data_10_out;
        end else if ((1'b1 == ap_CS_fsm_state24)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_mult_acc_data_8_out;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_mult_acc_data_6_out;
        end else if ((1'b1 == ap_CS_fsm_state16)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_mult_acc_data_4_out;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_mult_acc_data_2_out;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            result_TDATA_int_regslice = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_mult_acc_data_out;
        end else begin
            result_TDATA_int_regslice = 'bx;
        end
    end else begin
        result_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) & (result_TREADY_int_regslice == 1'b1))) begin
        result_TLAST_int_regslice = mult_acc_last_4_fu_860_p2;
    end else if (((1'b1 == ap_CS_fsm_state32) & (result_TREADY_int_regslice == 1'b1))) begin
        result_TLAST_int_regslice = mult_acc_last_3_reg_1158;
    end else if (((1'b1 == ap_CS_fsm_state24) & (result_TREADY_int_regslice == 1'b1))) begin
        result_TLAST_int_regslice = mult_acc_last_2_fu_692_p2;
    end else if (((1'b1 == ap_CS_fsm_state16) & (result_TREADY_int_regslice == 1'b1))) begin
        result_TLAST_int_regslice = mult_acc_last_1_fu_608_p2;
    end else if ((((1'b1 == ap_CS_fsm_state11) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state19) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state27) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state35) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state43) & (result_TREADY_int_regslice == 1'b1)))) begin
        result_TLAST_int_regslice = 1'd0;
    end else if (((1'b1 == ap_CS_fsm_state8) & (result_TREADY_int_regslice == 1'b1))) begin
        result_TLAST_int_regslice = mult_acc_last_fu_524_p2;
    end else begin
        result_TLAST_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state16) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state8) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state11) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state19) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state27) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state35) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state43) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state40) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state32) & (result_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state24) & (result_TREADY_int_regslice == 1'b1)))) begin
        result_TVALID_int_regslice = 1'b1;
    end else begin
        result_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln32_reg_993 == 1'd0) & (1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else if (((icmp_ln32_reg_993 == 1'd1) & (1'b1 == ap_CS_fsm_state9) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_CS_fsm_state11) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln32_1_reg_1048 == 1'd0) & (1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else if (((icmp_ln32_1_reg_1048 == 1'd1) & (1'b1 == ap_CS_fsm_state17) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            if (((icmp_ln32_2_reg_1103 == 1'd0) & (1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else if (((icmp_ln32_2_reg_1103 == 1'd1) & (1'b1 == ap_CS_fsm_state25) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == ap_CS_fsm_state32) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            if (((icmp_ln32_3_reg_1163 == 1'd0) & (1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else if (((icmp_ln32_3_reg_1163 == 1'd1) & (1'b1 == ap_CS_fsm_state33) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state34 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            if (((1'b1 == ap_CS_fsm_state35) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            if (((1'b1 == ap_CS_fsm_state36) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            if (((1'b1 == ap_CS_fsm_state40) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if ((~((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((1'b1 == ap_block_state41) | (result_TREADY_int_regslice == 1'b0)) & (icmp_ln32_4_reg_1213 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state43 : begin
            if (((1'b1 == ap_CS_fsm_state43) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end
        end
        ap_ST_fsm_state44 : begin
            if (((1'b1 == ap_CS_fsm_state44) & (result_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state41 = ((regslice_both_result_V_data_V_U_apdone_blk == 1'b1) | (result_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state41_ignore_call2 = ((regslice_both_result_V_data_V_U_apdone_blk == 1'b1) | (result_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i_i_0_fu_519_p2 = ((j_fu_134 == 16'd4) ? 1'b1 : 1'b0);

assign cmp_i_i_1_0_fu_603_p2 = ((j_2_fu_194 == 16'd4) ? 1'b1 : 1'b0);

assign cmp_i_i_2_0_fu_687_p2 = ((j_5_fu_198 == 16'd4) ? 1'b1 : 1'b0);

assign cmp_i_i_3_0_fu_743_p2 = ((j_8_fu_202 == 16'd4) ? 1'b1 : 1'b0);

assign cmp_i_i_4_0_fu_855_p2 = ((j_11_fu_206 == 16'd4) ? 1'b1 : 1'b0);

assign empty_19_fu_486_p1 = j_fu_134[4:0];

assign empty_20_fu_570_p1 = j_2_fu_194[4:0];

assign empty_21_fu_654_p1 = j_5_fu_198[4:0];

assign empty_22_fu_738_p1 = j_8_fu_202[4:0];

assign empty_23_fu_822_p1 = j_11_fu_206[4:0];

assign grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP1_fu_387_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP2_fu_396_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP3_fu_405_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP4_fu_414_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP5_fu_423_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP6_fu_432_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP7_fu_441_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP8_fu_450_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP9_fu_459_ap_start_reg;

assign grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start = grp_array_mult_Pipeline_MULT_ACC_LOOP_fu_378_ap_start_reg;

assign grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start = grp_array_mult_Pipeline_VITIS_LOOP_26_1_fu_362_ap_start_reg;

assign icmp_ln32_1_fu_593_p2 = (($signed(j_4_fu_585_p3) < $signed(16'd5)) ? 1'b1 : 1'b0);

assign icmp_ln32_2_fu_677_p2 = (($signed(j_7_fu_669_p3) < $signed(16'd5)) ? 1'b1 : 1'b0);

assign icmp_ln32_3_fu_772_p2 = (($signed(j_22_fu_764_p3) < $signed(16'd5)) ? 1'b1 : 1'b0);

assign icmp_ln32_4_fu_845_p2 = (($signed(j_25_fu_837_p3) < $signed(16'd5)) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_509_p2 = (($signed(j_1_fu_501_p3) < $signed(16'd5)) ? 1'b1 : 1'b0);

assign in_a_TREADY = regslice_both_in_a_V_data_V_U_ack_in;

assign j_16_fu_548_p2 = (j_fu_134 + 16'd2);

assign j_18_fu_632_p2 = (j_2_fu_194 + 16'd2);

assign j_1_fu_501_p3 = {{tmp_fu_491_p4}, {1'd1}};

assign j_20_fu_716_p2 = (j_5_fu_198 + 16'd2);

assign j_22_fu_764_p3 = {{tmp_6_fu_754_p4}, {1'd1}};

assign j_23_fu_800_p2 = (j_8_fu_202 + 16'd2);

assign j_25_fu_837_p3 = {{tmp_8_fu_827_p4}, {1'd1}};

assign j_26_fu_884_p2 = (j_11_fu_206 + 16'd2);

assign j_4_fu_585_p3 = {{tmp_2_fu_575_p4}, {1'd1}};

assign j_7_fu_669_p3 = {{tmp_4_fu_659_p4}, {1'd1}};

assign mult_acc_last_1_fu_608_p2 = (in_a_store_last_load_1_reg_1035 & cmp_i_i_1_0_fu_603_p2);

assign mult_acc_last_2_fu_692_p2 = (in_a_store_last_load_2_reg_1090 & cmp_i_i_2_0_fu_687_p2);

assign mult_acc_last_3_fu_749_p2 = (in_a_store_last_load_3_reg_1145 & cmp_i_i_3_0_fu_743_p2);

assign mult_acc_last_4_fu_860_p2 = (in_a_store_last_load_4_reg_1200 & cmp_i_i_4_0_fu_855_p2);

assign mult_acc_last_fu_524_p2 = (in_a_store_last_load_reg_980 & cmp_i_i_0_fu_519_p2);

assign or_ln36_1_fu_623_p3 = {{tmp_3_fu_614_p4}, {1'd1}};

assign or_ln36_2_fu_707_p3 = {{tmp_5_fu_698_p4}, {1'd1}};

assign or_ln36_3_fu_791_p3 = {{tmp_7_fu_782_p4}, {1'd1}};

assign or_ln36_4_fu_875_p3 = {{tmp_9_fu_866_p4}, {1'd1}};

assign or_ln_fu_539_p3 = {{tmp_1_fu_530_p4}, {1'd1}};

assign result_TVALID = regslice_both_result_V_data_V_U_vld_out;

assign tmp_1_fu_530_p4 = {{j_fu_134[4:1]}};

assign tmp_2_fu_575_p4 = {{j_2_fu_194[15:1]}};

assign tmp_3_fu_614_p4 = {{j_2_fu_194[4:1]}};

assign tmp_4_fu_659_p4 = {{j_5_fu_198[15:1]}};

assign tmp_5_fu_698_p4 = {{j_5_fu_198[4:1]}};

assign tmp_6_fu_754_p4 = {{j_8_fu_202[15:1]}};

assign tmp_7_fu_782_p4 = {{j_8_fu_202[4:1]}};

assign tmp_8_fu_827_p4 = {{j_11_fu_206[15:1]}};

assign tmp_9_fu_866_p4 = {{j_11_fu_206[4:1]}};

assign tmp_fu_491_p4 = {{j_fu_134[15:1]}};

always @ (posedge ap_clk) begin
    or_ln_reg_1005[0] <= 1'b1;
    or_ln36_1_reg_1060[0] <= 1'b1;
    or_ln36_2_reg_1115[0] <= 1'b1;
    or_ln36_3_reg_1170[0] <= 1'b1;
    or_ln36_4_reg_1225[0] <= 1'b1;
end

endmodule //array_mult
