# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_processing_system7_0_0/main_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_processing_system7_0_0 || ORIG_REF_NAME==main_processing_system7_0_0} -quiet] -quiet

# IP: bd/main/ip/main_proc_sys_reset_0_0/main_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_proc_sys_reset_0_0 || ORIG_REF_NAME==main_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/Users/james/Documents/repos/FPGA/lab1/lab1.gen/sources_1/bd/main/main_ooc.xdc
