domain_path: C:\Users\james\Documents\repos\FPGA\lab1\vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
